[package]
name = "fgdb-collections"
version = "0.0.1"
edition = "2024"
description = "Deterministic in-memory collection kernels for FrankenGraphDB."
publish = false

[dependencies]
fgdb-types = { path = "../fgdb-types" }
fgdb-unsafe-arena = { path = "../fgdb-unsafe-arena" }

[dev-dependencies]
asupersync = { git = "https://github.com/Dicklesworthstone/asupersync", rev = "78b64636e99fea4ea2d868096576021dd3b8e519", version = "=0.5.0", default-features = false, features = ["test-internals"] }

[lints]
workspace = true
