[package]
name = "fgdb-collections"
version = "0.0.1"
edition = "2024"
description = "Deterministic in-memory collection kernels for FrankenGraphDB."
publish = false

[dependencies]
fgdb-types = { path = "../fgdb-types" }
fgdb-unsafe-arena = { path = "../fgdb-unsafe-arena" }

[dev-dependencies]
asupersync = { git = "https://github.com/Dicklesworthstone/asupersync", rev = "3e8d08efe6617e08635fa8705c62a2a531373f43", default-features = false, features = ["test-internals"] }

[lints]
workspace = true
