//! Typed mutation and property suite for the G0 threat/trust model
//! (fgdb-g0-threat-model-nqd).
//!
//! Two kinds of test live here, and the distinction matters:
//!
//!   * **Registry mutation fixtures** take the frozen registry, break exactly
//!     one thing, and assert the checker reports the exact violation code. A
//!     checker nobody has watched go red is a checker nobody knows works.
//!   * **Attenuation property tests** run pseudo-random chains against the
//!     narrowing operators the REGISTRY declares, not against a hand-copied
//!     table. If the registry's operators drift, these fail — which is the
//!     point of deriving the lattice order from the registry.
//!
//! Determinism by default applies here too: the chain generator is a seeded
//! xorshift, so a failure is a seed, never a flake.

use registry_check::threat::{
    self, ThreatRegistry, expand_exposures, expand_footprint, expand_product_space, load_from_repo,
    scan_claims, validate_threat,
};
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace root")
        .to_path_buf()
}

fn registry() -> ThreatRegistry {
    load_from_repo(&repo_root()).expect("threat_model.toml loads")
}

fn registry_text() -> String {
    std::fs::read_to_string(repo_root().join(threat::REGISTRY_PATH))
        .expect("read threat_model.toml")
}

/// Apply one textual mutation and return the violation codes it produces.
/// Panics if the mutation did not apply — a fixture that silently no-ops is a
/// fixture that passes for the wrong reason.
fn codes_after(original: &str, replacement: &str) -> Vec<String> {
    codes_after_all(&[(original, replacement)])
}

/// Apply several mutations in order. Needed when a single edit would produce a
/// DIFFERENT defect than the one under test — swapping two ordinals takes two
/// edits, and doing only half of it tests ordinal collision instead of order.
fn codes_after_all(edits: &[(&str, &str)]) -> Vec<String> {
    let mut text = registry_text();
    for (original, replacement) in edits {
        assert_eq!(
            text.matches(original).count(),
            1,
            "mutation anchor {original:?} must occur exactly once"
        );
        text = text.replacen(original, replacement, 1);
    }
    let mutated = text;
    let parsed = match threat::parse_threat(&mutated) {
        Ok(parsed) => parsed,
        // A mutation that makes the registry unparseable is also a rejection;
        // report it under a synthetic code so the fixture can assert on it.
        Err(error) => return vec![format!("load_error:{}", error.message)],
    };
    validate_threat(&parsed, &repo_root())
        .into_iter()
        .map(|violation| violation.code)
        .collect()
}

fn assert_code(codes: &[String], expected: &str) {
    assert!(
        codes.iter().any(|code| code == expected),
        "expected violation {expected:?}, got {codes:?}"
    );
}

// -----------------------------------------------------------------------------
// Baseline
// -----------------------------------------------------------------------------

#[test]
fn tm_registry_is_clean() {
    let violations = validate_threat(&registry(), &repo_root());
    assert!(
        violations.is_empty(),
        "frozen threat model must validate clean, found: {violations:?}"
    );
}

#[test]
fn tm_document_matches_registry() {
    let registry = registry();
    assert!(
        threat::check_document(&registry, &repo_root()).expect("document regenerates"),
        "docs/THREAT_AND_TRUST_MODEL.md differs from the regenerated bytes; run threat-check --write"
    );
}

#[test]
fn tm_document_generation_is_deterministic() {
    let registry = registry();
    let first = threat::generate_document(&registry, &repo_root()).expect("generate");
    let second = threat::generate_document(&registry, &repo_root()).expect("generate");
    assert_eq!(first, second);
}

// -----------------------------------------------------------------------------
// tm_actor_asset_assumption_complete
// -----------------------------------------------------------------------------

#[test]
fn tm_actor_asset_assumption_complete() {
    let registry = registry();
    let cells = expand_exposures(&registry);
    assert_eq!(
        cells.len(),
        registry.actors.len() * registry.assets.len(),
        "the exposure matrix must be complete"
    );
    for actor in &registry.actors {
        for asset in &registry.assets {
            let found: Vec<_> = cells
                .iter()
                .filter(|cell| cell.actor_id == actor.id && cell.asset_id == asset.id)
                .collect();
            assert_eq!(
                found.len(),
                1,
                "actor {} x asset {} must be dispositioned exactly once",
                actor.id,
                asset.id
            );
            let cell = found[0];
            assert!(
                registry
                    .assumptions
                    .iter()
                    .any(|assumption| assumption.id == cell.assumption_id),
                "cell {}/{} names unregistered assumption {}",
                actor.id,
                asset.id,
                cell.assumption_id
            );
        }
    }
}

#[test]
fn tm_neg_exposure_cell_dropped() {
    // Drop one cell from the compromised-server row: the actor whose undefended
    // list is the whole point of the model.
    let codes = codes_after("  \"key_material:A-NO-TEE\",\n", "");
    assert_code(&codes, "exposure_missing");
}

#[test]
fn tm_neg_exposure_unknown_assumption() {
    let codes = codes_after(
        "\"plaintext_graph_data:A-NO-TEE\",",
        "\"plaintext_graph_data:A-INVENTED-COMFORT\",",
    );
    assert_code(&codes, "exposure_unknown_assumption");
}

// -----------------------------------------------------------------------------
// tm_footprint_all_postures_eleven_authorities / tm_directorybound_footprint_empty
// -----------------------------------------------------------------------------

#[test]
fn tm_footprint_all_postures_eleven_authorities() {
    let registry = registry();
    assert_eq!(registry.external_authorities.len(), 11);
    let cells = expand_footprint(&registry);
    assert_eq!(cells.len(), registry.postures.len() * 11);
    for cell in &cells {
        assert_ne!(
            cell.status, "missing",
            "posture {} has no declaration for authority {}",
            cell.posture_id, cell.authority_id
        );
    }
    for posture in &registry.postures {
        for authority in &registry.external_authorities {
            assert!(
                cells
                    .iter()
                    .any(|cell| cell.posture_id == posture.id && cell.authority_id == authority.id),
                "missing cell {}/{}",
                posture.id,
                authority.id
            );
        }
    }
}

#[test]
fn tm_directorybound_footprint_empty() {
    let registry = registry();
    let posture = registry
        .postures
        .iter()
        .find(|posture| posture.id == "local_directory_bound")
        .expect("the embedded DirectoryBound posture is registered");
    assert_eq!(posture.continuity_profile, "DirectoryBound");
    assert_eq!(posture.footprint_declaration, "empty");
    assert!(!posture.empty_justification.trim().is_empty());
    assert!(
        !registry
            .footprints
            .iter()
            .any(|row| row.posture_id == posture.id),
        "the embedded DirectoryBound posture consumes zero external authorities"
    );
    for cell in expand_footprint(&registry)
        .iter()
        .filter(|cell| cell.posture_id == posture.id)
    {
        assert_eq!(cell.status, "empty_declared");
        assert!(!cell.on_synchronous_path);
        assert_eq!(cell.touch_count, 0);
    }
}

#[test]
fn tm_neg_footprint_cell_dropped() {
    let text = registry_text();
    let anchor = "[[footprint]]\nposture_id = \"local_external_cas\"\nauthority_id = \"kms_hsm\"";
    let start = text.find(anchor).expect("kms_hsm footprint row");
    let end = text[start..]
        .find("\n\n")
        .map(|offset| start + offset + 2)
        .expect("row terminator");
    let mutated = format!("{}{}", &text[..start], &text[end..]);
    let parsed = threat::parse_threat(&mutated).expect("still parses");
    let codes: Vec<String> = validate_threat(&parsed, &repo_root())
        .into_iter()
        .map(|violation| violation.code)
        .collect();
    assert_code(&codes, "footprint_cell_missing");
}

#[test]
fn tm_neg_footprint_invents_operation_class() {
    // The honesty law: a trigger_site_only cell may not name an operation class
    // the source never named.
    let codes = codes_after(
        "operation_class_basis = \"trigger_site_only\"\noperation_classes = []\ndeferred_binding_owner = \"fgdb-w9-authority-surface-gp9j\"\n\n[[footprint]]\nposture_id = \"local_external_cas\"\nauthority_id = \"cluster_incarnation\"",
        "operation_class_basis = \"trigger_site_only\"\noperation_classes = [\"Admin\"]\ndeferred_binding_owner = \"fgdb-w9-authority-surface-gp9j\"\n\n[[footprint]]\nposture_id = \"local_external_cas\"\nauthority_id = \"cluster_incarnation\"",
    );
    assert_code(&codes, "footprint_unsourced_operation_class");
}

// -----------------------------------------------------------------------------
// Posture product-space closure
// -----------------------------------------------------------------------------

#[test]
fn tm_posture_product_space_is_closed() {
    let registry = registry();
    let cells = expand_product_space(&registry);
    assert_eq!(cells.len(), 12, "2 x 2 x 3 product space");
    for cell in &cells {
        assert_ne!(
            cell.resolution, "unresolved",
            "cell {}/{}/{} is neither registered, deferred, nor excluded",
            cell.service_class, cell.role_posture, cell.continuity_profile
        );
        assert!(!cell.resolved_by.is_empty());
    }
    let registered = cells
        .iter()
        .filter(|c| c.resolution == "registered")
        .count();
    let deferred = cells.iter().filter(|c| c.resolution == "deferred").count();
    let excluded = cells.iter().filter(|c| c.resolution == "excluded").count();
    assert_eq!((registered, deferred, excluded), (2, 2, 8));
}

#[test]
fn tm_neg_posture_in_excluded_cell() {
    // A Sharded DirectoryBound posture contradicts PX-1.
    let codes = codes_after(
        "role_posture = \"Sharded\"\ncontinuity_profile = \"ExternalCas\"\nowner_bead = \"fgdb-w12-meta-authority-transfer\"",
        "role_posture = \"Sharded\"\ncontinuity_profile = \"DirectoryBound\"\nowner_bead = \"fgdb-w12-meta-authority-transfer\"",
    );
    assert_code(&codes, "posture_excluded_cell");
}

#[test]
fn tm_neg_admissible_cell_unowned() {
    // Delete the deferred sharded posture: the admissible cell it covered is
    // then unresolved, which is exactly the silent-deployment-drop this law
    // exists to prevent.
    let text = registry_text();
    let anchor = "[[deferred_posture]]\nid = \"sharded_external_cas\"";
    let start = text.find(anchor).expect("sharded deferred posture");
    let end = text[start..]
        .find("\n\n")
        .map(|offset| start + offset + 2)
        .expect("row terminator");
    let mutated = format!("{}{}", &text[..start], &text[end..]);
    let parsed = threat::parse_threat(&mutated).expect("still parses");
    let codes: Vec<String> = validate_threat(&parsed, &repo_root())
        .into_iter()
        .map(|violation| violation.code)
        .collect();
    assert_code(&codes, "product_cell_unresolved");
}

// -----------------------------------------------------------------------------
// tm_epoch_types_do_not_unify
// -----------------------------------------------------------------------------

/// G0 proves distinct registry identities, wire tags, Rust declarations, and
/// epoch domains for the security and adaptive epoch types.
#[test]
fn tm_epoch_types_do_not_unify() {
    let registry = registry();
    let security = registry
        .identities
        .iter()
        .find(|identity| identity.name == "SecurityPolicyEpoch")
        .expect("SecurityPolicyEpoch registered");
    let decision = registry
        .identities
        .iter()
        .find(|identity| identity.name == "DecisionPolicyEpoch")
        .expect("DecisionPolicyEpoch registered");
    assert_ne!(security.epoch_domain, decision.epoch_domain);
    assert_eq!(security.epoch_domain, "security");
    assert_eq!(decision.epoch_domain, "adaptive");
    assert_ne!(security.rust_newtype, decision.rust_newtype);
    assert_ne!(security.wire_tag, decision.wire_tag);
    assert_eq!(security.kind, "security_epoch");
    assert_eq!(decision.kind, "adaptive_epoch");
}

#[test]
fn tm_neg_epoch_domains_unified() {
    let codes = codes_after(
        "rust_newtype = \"DecisionPolicyEpoch\"\nwire_tag = \"fgdb:adaptive-epoch:decision-policy-epoch:v1\"",
        "rust_newtype = \"SecurityPolicyEpoch\"\nwire_tag = \"fgdb:security-epoch:security-policy-epoch:v1\"",
    );
    assert_code(&codes, "identity_newtype_collision");
    assert_code(&codes, "epoch_identities_unify");
}

#[test]
fn tm_neg_identity_rust_newtype_missing() {
    let codes = codes_after(
        "rust_newtype = \"TenantId\"",
        "rust_newtype = \"MissingTenantId\"",
    );
    assert_code(&codes, "identity_rust_newtype_missing");
}

// -----------------------------------------------------------------------------
// The attenuation property suite
// -----------------------------------------------------------------------------

/// One dimension's value under the model. The variant is chosen by the
/// registry's declared narrowing operator, so the property suite cannot drift
/// from the frozen lattice order.
#[derive(Debug, Clone, PartialEq, Eq)]
enum DimValue {
    /// `fixed` — identical in every link.
    Fixed(u64),
    /// `intersect` — subsets only.
    Scope(Vec<u64>),
    /// `raise_only` — the bound may only move up.
    LowerBound(i64),
    /// `lower_only` — the bound may only move down.
    UpperBound(i64),
    /// `append_only` — entries may only be added.
    Appended(Vec<u64>),
    /// `restrict_disclosure_only` / `restrict_binding_only` — rank may only rise.
    Rank(u64),
    /// `current_state_monotone` — supplied by current state, monotone.
    Monotone(u64),
}

impl DimValue {
    fn seed(operator: &str, seed: u64) -> DimValue {
        match operator {
            "fixed" => DimValue::Fixed(seed),
            "intersect" => DimValue::Scope((0..8).map(|index| seed.wrapping_add(index)).collect()),
            "raise_only" => DimValue::LowerBound(0),
            "lower_only" => DimValue::UpperBound(1_000_000),
            "append_only" => DimValue::Appended(vec![seed]),
            "restrict_disclosure_only" | "restrict_binding_only" => DimValue::Rank(0),
            "current_state_monotone" => DimValue::Monotone(0),
            other => panic!("unmodelled narrowing operator {other:?}"),
        }
    }
}

/// Does `next` narrow `prior` under this operator? This is the whole lattice
/// order, in one function.
fn narrows(prior: &DimValue, next: &DimValue) -> bool {
    match (prior, next) {
        (DimValue::Fixed(a), DimValue::Fixed(b)) => a == b,
        (DimValue::Scope(a), DimValue::Scope(b)) => b.iter().all(|item| a.contains(item)),
        (DimValue::LowerBound(a), DimValue::LowerBound(b)) => b >= a,
        (DimValue::UpperBound(a), DimValue::UpperBound(b)) => b <= a,
        (DimValue::Appended(a), DimValue::Appended(b)) => {
            b.len() >= a.len() && b[..a.len()] == a[..]
        }
        (DimValue::Rank(a), DimValue::Rank(b)) => b >= a,
        (DimValue::Monotone(a), DimValue::Monotone(b)) => b >= a,
        _ => false,
    }
}

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*: deterministic, seeded, no dependency. A failing case is
        // a seed, not a flake.
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }

    fn below(&mut self, bound: usize) -> usize {
        if bound == 0 {
            0
        } else {
            (self.next() % bound as u64) as usize
        }
    }
}

/// Produce a legal narrowing successor for one dimension.
fn narrow_once(value: &DimValue, rng: &mut Rng) -> DimValue {
    match value {
        DimValue::Fixed(inner) => DimValue::Fixed(*inner),
        DimValue::Scope(items) => {
            if items.len() <= 1 {
                DimValue::Scope(items.clone())
            } else {
                let drop = rng.below(items.len());
                let mut next = items.clone();
                next.remove(drop);
                DimValue::Scope(next)
            }
        }
        DimValue::LowerBound(bound) => {
            DimValue::LowerBound(bound.saturating_add((rng.below(5)) as i64))
        }
        DimValue::UpperBound(bound) => {
            DimValue::UpperBound(bound.saturating_sub((rng.below(5)) as i64))
        }
        DimValue::Appended(items) => {
            let mut next = items.clone();
            next.push(rng.next());
            DimValue::Appended(next)
        }
        DimValue::Rank(rank) => DimValue::Rank((rank + rng.below(2) as u64).min(2)),
        DimValue::Monotone(value) => DimValue::Monotone(value + rng.below(3) as u64),
    }
}

/// Produce an ILLEGAL widening successor, or `None` when the value is already
/// at a bound where widening is not expressible.
fn widen_once(value: &DimValue) -> Option<DimValue> {
    match value {
        DimValue::Fixed(inner) => Some(DimValue::Fixed(inner.wrapping_add(1))),
        DimValue::Scope(items) => {
            let mut next = items.clone();
            next.push(u64::MAX);
            Some(DimValue::Scope(next))
        }
        DimValue::LowerBound(bound) => Some(DimValue::LowerBound(bound - 1)),
        DimValue::UpperBound(bound) => Some(DimValue::UpperBound(bound + 1)),
        DimValue::Appended(items) if !items.is_empty() => {
            Some(DimValue::Appended(items[..items.len() - 1].to_vec()))
        }
        DimValue::Appended(_) => None,
        DimValue::Rank(rank) if *rank > 0 => Some(DimValue::Rank(rank - 1)),
        DimValue::Rank(_) => None,
        DimValue::Monotone(value) if *value > 0 => Some(DimValue::Monotone(value - 1)),
        DimValue::Monotone(_) => None,
    }
}

/// tm_attenuation_narrowing_only — random chains over EVERY registered
/// dimension may only narrow, and every expressible widening mutation of every
/// dimension is rejected.
#[test]
fn tm_attenuation_narrowing_only() {
    let registry = registry();
    let operators: Vec<(String, String)> = registry
        .authority_dimensions
        .iter()
        .map(|dimension| (dimension.id.clone(), dimension.narrowing_operator.clone()))
        .collect();
    assert_eq!(
        operators.len(),
        27,
        "every §12.1/§12.2 dimension is modelled"
    );

    let mut widened_at_least_once = 0usize;
    for seed in 1u64..=256 {
        let mut rng = Rng(seed.wrapping_mul(0x9e37_79b9_7f4a_7c15) | 1);
        let mut chain: Vec<Vec<DimValue>> = vec![
            operators
                .iter()
                .map(|(_, operator)| DimValue::seed(operator, seed))
                .collect(),
        ];
        for _ in 0..6 {
            let prior = chain.last().expect("non-empty chain").clone();
            let next: Vec<DimValue> = prior
                .iter()
                .map(|value| narrow_once(value, &mut rng))
                .collect();
            chain.push(next);
        }
        // Every adjacent pair narrows, and narrowing is transitive along the
        // whole chain — a link cannot launder a widening through intermediates.
        for window in chain.windows(2) {
            for (index, (prior, next)) in window[0].iter().zip(&window[1]).enumerate() {
                assert!(
                    narrows(prior, next),
                    "seed {seed}: dimension {} widened: {prior:?} -> {next:?}",
                    operators[index].0
                );
            }
        }
        let first = chain.first().expect("non-empty");
        let last = chain.last().expect("non-empty");
        for (index, (prior, next)) in first.iter().zip(last).enumerate() {
            assert!(
                narrows(prior, next),
                "seed {seed}: dimension {} widened across the chain",
                operators[index].0
            );
        }
        // Every expressible widening mutation is rejected.
        for (index, value) in last.iter().enumerate() {
            if let Some(widened) = widen_once(value) {
                assert!(
                    !narrows(value, &widened),
                    "seed {seed}: widening dimension {} was accepted: {value:?} -> {widened:?}",
                    operators[index].0
                );
                widened_at_least_once += 1;
            }
        }
    }
    assert!(
        widened_at_least_once > 0,
        "the widening half of the property must not be vacuous"
    );
}

#[test]
fn tm_neg_time_extension() {
    // ATT-X1: a link cannot extend time in either direction.
    assert!(!narrows(
        &DimValue::LowerBound(100),
        &DimValue::LowerBound(99)
    ));
    assert!(!narrows(
        &DimValue::UpperBound(100),
        &DimValue::UpperBound(101)
    ));
    assert!(narrows(
        &DimValue::LowerBound(100),
        &DimValue::LowerBound(101)
    ));
    assert!(narrows(
        &DimValue::UpperBound(100),
        &DimValue::UpperBound(99)
    ));
    let registry = registry();
    let law = registry
        .attenuation_laws
        .iter()
        .find(|law| law.id == "ATT-X1")
        .expect("ATT-X1 registered");
    assert_eq!(law.class, "prohibited");
    assert_eq!(law.negative_fixture, "tm_neg_time_extension");
}

#[test]
fn tm_neg_domain_change() {
    // ATT-X2: the authority domain is fixed across every link.
    assert!(narrows(&DimValue::Fixed(7), &DimValue::Fixed(7)));
    assert!(!narrows(&DimValue::Fixed(7), &DimValue::Fixed(8)));
    let registry = registry();
    let law = registry
        .attenuation_laws
        .iter()
        .find(|law| law.id == "ATT-X2")
        .expect("ATT-X2 registered");
    // Every domain dimension must actually be `fixed`; a domain dimension that
    // could intersect would let a chain narrow its way to a different tenant.
    for dimension_id in &law.dimension_ids {
        let dimension = registry
            .authority_dimensions
            .iter()
            .find(|dimension| &dimension.id == dimension_id)
            .expect("dimension resolves");
        assert_eq!(
            dimension.narrowing_operator, "fixed",
            "authority-domain dimension {dimension_id} must be fixed"
        );
    }
}

#[test]
fn tm_neg_binding_weakening() {
    // ATT-X5: Session/Channel binding never moves to a less restrictive class.
    let registry = registry();
    let rank = |name: &str| {
        registry
            .presentation_bindings
            .iter()
            .find(|binding| binding.name == name)
            .expect("binding registered")
            .rank
    };
    assert!(rank("ServerInternal") < rank("SessionBound"));
    assert!(rank("SessionBound") < rank("ChannelBound"));
    for transition in &registry.binding_transitions {
        let expected = rank(&transition.to) >= rank(&transition.from);
        assert_eq!(
            transition.legal, expected,
            "transition {}->{} legality contradicts the rank order",
            transition.from, transition.to
        );
    }
    let illegal: Vec<_> = registry
        .binding_transitions
        .iter()
        .filter(|transition| !transition.legal)
        .collect();
    assert_eq!(illegal.len(), 3, "exactly three weakening cells");
    for transition in illegal {
        assert_eq!(transition.law, "weakened_binding");
    }
    assert!(!narrows(&DimValue::Rank(2), &DimValue::Rank(1)));
}

#[test]
fn tm_neg_scope_widening() {
    assert!(narrows(
        &DimValue::Scope(vec![1, 2, 3]),
        &DimValue::Scope(vec![1, 3])
    ));
    assert!(!narrows(
        &DimValue::Scope(vec![1, 2]),
        &DimValue::Scope(vec![1, 2, 3])
    ));
}

#[test]
fn tm_neg_caveat_removal() {
    assert!(narrows(
        &DimValue::Appended(vec![1, 2]),
        &DimValue::Appended(vec![1, 2, 3])
    ));
    assert!(!narrows(
        &DimValue::Appended(vec![1, 2]),
        &DimValue::Appended(vec![1])
    ));
    // Rewriting an existing caveat is not appending.
    assert!(!narrows(
        &DimValue::Appended(vec![1, 2]),
        &DimValue::Appended(vec![9, 2, 3])
    ));
}

#[test]
fn tm_neg_disclosure_widening() {
    let registry = registry();
    let dimension = registry
        .authority_dimensions
        .iter()
        .find(|dimension| dimension.id == "redaction_profile")
        .expect("redaction_profile registered");
    assert_eq!(dimension.narrowing_operator, "restrict_disclosure_only");
    assert!(!narrows(&DimValue::Rank(1), &DimValue::Rank(0)));
}

#[test]
fn tm_neg_cohort_move() {
    let registry = registry();
    let law = registry
        .attenuation_laws
        .iter()
        .find(|law| law.id == "ATT-X4")
        .expect("ATT-X4 registered");
    assert_eq!(law.class, "prohibited");
    for dimension_id in &law.dimension_ids {
        let dimension = registry
            .authority_dimensions
            .iter()
            .find(|dimension| &dimension.id == dimension_id)
            .expect("dimension resolves");
        assert_eq!(dimension.narrowing_operator, "fixed");
    }
}

#[test]
fn tm_every_prohibition_names_a_live_fixture() {
    // The fixtures named by the registry must be tests that exist in this file.
    let source = include_str!("threat_model.rs");
    let registry = registry();
    for law in &registry.attenuation_laws {
        assert!(
            source.contains(&format!("fn {}(", law.negative_fixture)),
            "attenuation law {} names fixture {}, which is not defined in this suite",
            law.id,
            law.negative_fixture
        );
    }
}

#[test]
fn tm_neg_binding_transition_legality_flipped() {
    let codes = codes_after(
        "[[binding_transition]]\nfrom = \"ChannelBound\"\nto = \"SessionBound\"\nlegal = false\nlaw = \"weakened_binding\"",
        "[[binding_transition]]\nfrom = \"ChannelBound\"\nto = \"SessionBound\"\nlegal = true\nlaw = \"further_restrict\"",
    );
    assert_code(&codes, "binding_transition_legality");
}

#[test]
fn tm_neg_dimension_ungoverned() {
    // Give a dimension an operator no attenuation law governs.
    let codes = codes_after(
        "id = \"redaction_profile\"\nsource_order = 22\nnarrowing_operator = \"restrict_disclosure_only\"",
        "id = \"redaction_profile_renamed\"\nsource_order = 22\nnarrowing_operator = \"restrict_disclosure_only\"",
    );
    assert_code(&codes, "dimension_ungoverned");
    assert_code(&codes, "attenuation_law_unknown_dimension");
}

// -----------------------------------------------------------------------------
// tm_no_compromised_server_confidentiality_claim
// -----------------------------------------------------------------------------

#[test]
fn tm_no_compromised_server_confidentiality_claim() {
    let registry = registry();
    let document = threat::generate_document(&registry, &repo_root()).expect("generate");
    let hits = scan_claims(&document, &registry);
    assert!(
        hits.is_empty(),
        "the generated normative text asserts more than the trust matrix admits: {hits:?}"
    );
    // The model must SAY the exposure, not merely avoid denying it.
    let compromised = registry
        .actors
        .iter()
        .find(|actor| actor.id == "compromised_operator_or_server")
        .expect("the compromised-server actor is registered");
    assert!(
        compromised.defended_assets.is_empty(),
        "no asset is defended against a compromised server process"
    );
    assert!(
        compromised
            .undefended_assets
            .iter()
            .any(|entry| entry.starts_with("plaintext_graph_data:")),
        "plaintext must be declared undefended against a compromised server process"
    );
}

#[test]
fn tm_claim_scan_rejects_an_overreaching_sentence() {
    // The scan must go red on a real overreach, or its green means nothing.
    let registry = registry();
    let overreach = "Graph data stays confidential even against a compromised server, by design.";
    let hits = scan_claims(overreach, &registry);
    assert!(
        hits.iter().any(|hit| hit.rule_id == "TMS-1"),
        "TMS-1 must flag a confidentiality claim against a compromised server: {hits:?}"
    );
}

#[test]
fn tm_claim_scan_rules_are_all_exercised() {
    // Every rule fires on at least one crafted overreach. A rule nobody has
    // seen fire is a rule that may be syntactically incapable of firing.
    let registry = registry();
    let probes = [
        (
            "TMS-1",
            "Data remains confidential against a compromised server.",
        ),
        ("TMS-2", "The cluster tolerates Byzantine replicas."),
        ("TMS-3", "These fixtures prove noninterference."),
        ("TMS-4", "A witness can undo the disclosure."),
    ];
    for (rule_id, sentence) in probes {
        let hits = scan_claims(sentence, &registry);
        assert!(
            hits.iter().any(|hit| hit.rule_id == rule_id),
            "rule {rule_id} did not fire on {sentence:?}: {hits:?}"
        );
    }
}

// -----------------------------------------------------------------------------
// Schema hygiene
// -----------------------------------------------------------------------------

#[test]
fn tm_schema_denies_unknown_keys() {
    let codes = codes_after(
        "id = \"untrusted_client\"\ntitle = \"Untrusted client\"",
        "id = \"untrusted_client\"\nsmuggled_key = \"surprise\"\ntitle = \"Untrusted client\"",
    );
    assert!(
        codes.iter().any(|code| code.starts_with("load_error:")),
        "an unknown key must fail closed at load, got {codes:?}"
    );
}

#[test]
fn tm_neg_count_drift() {
    let codes = codes_after("actor_count = 8", "actor_count = 7");
    assert_code(&codes, "count_drift");
}

#[test]
fn tm_neg_source_block_drift() {
    let codes = codes_after(
        "plan_end_line = 864\nline_count = 5",
        "plan_end_line = 863\nline_count = 4",
    );
    assert_code(&codes, "source_block_drift");
}

#[test]
fn tm_neg_semantic_contract_hash_drift() {
    // Any semantic edit must move the contract hash. Change one disposition.
    let codes = codes_after(
        "  \"derived_state_and_observable_metadata:A-NO-TEE\",",
        "  \"derived_state_and_observable_metadata:A-PROCESS-TRUSTED\",",
    );
    assert_code(&codes, "semantic_contract_hash");
}

#[test]
fn tm_operation_classes_are_the_closed_sixteen_in_source_order() {
    let registry = registry();
    let mut classes: Vec<_> = registry.operation_classes.iter().collect();
    classes.sort_by_key(|class| class.ordinal);
    let names: Vec<&str> = classes.iter().map(|class| class.name.as_str()).collect();
    assert_eq!(names, threat::OPERATION_CLASS_ORDER);
}

#[test]
fn tm_neg_operation_class_alphabetized() {
    // Census order is alphabetical; source order is normative. A genuine SWAP
    // keeps the set and the density intact and must still be rejected.
    let codes = codes_after_all(&[
        (
            "name = \"Read\"\nordinal = 1",
            "name = \"Read\"\nordinal = 16",
        ),
        (
            "name = \"Replicate\"\nordinal = 16",
            "name = \"Replicate\"\nordinal = 1",
        ),
    ]);
    assert_code(&codes, "operation_class_order");
    // ... and the half-swap must be caught by a DIFFERENT law, so neither
    // defect can hide behind the other.
    let half = codes_after(
        "name = \"Read\"\nordinal = 1",
        "name = \"Read\"\nordinal = 2",
    );
    assert_code(&half, "ordinal_collision");
}

#[test]
fn tm_external_authorities_are_the_eleven_in_source_order() {
    let registry = registry();
    let mut authorities: Vec<_> = registry.external_authorities.iter().collect();
    authorities.sort_by_key(|authority| authority.source_order);
    let ids: Vec<&str> = authorities
        .iter()
        .map(|authority| authority.id.as_str())
        .collect();
    assert_eq!(ids, threat::EXTERNAL_AUTHORITY_ORDER);
}

#[test]
fn tm_actors_are_the_eight_in_source_order() {
    let registry = registry();
    let mut actors: Vec<_> = registry.actors.iter().collect();
    actors.sort_by_key(|actor| actor.source_order);
    let ids: Vec<&str> = actors.iter().map(|actor| actor.id.as_str()).collect();
    assert_eq!(ids, threat::ACTOR_ORDER);
}

#[test]
fn tm_registered_rejections_cover_the_plan_rejections() {
    let registry = registry();
    let ids: Vec<&str> = registry
        .out_of_scope
        .iter()
        .map(|row| row.id.as_str())
        .collect();
    for expected in [
        "OOS-FHE-MPC-ORAM",
        "OOS-TEE",
        "OOS-BYZANTINE-CONSENSUS",
        "OOS-TRUETIME",
        "OOS-NONINTERFERENCE-PROOF",
    ] {
        assert!(ids.contains(&expected), "missing rejection {expected}");
    }
}

#[test]
fn tm_bound_claims_resolve_to_live_registry_rows() {
    let registry = registry();
    let invariants = std::fs::read_to_string(repo_root().join("registries/invariants.toml"))
        .expect("invariants");
    for id in &registry.registry.bound_invariants {
        assert!(
            invariants.contains(&format!("id = \"{id}\"")),
            "bound invariant {id} is not a live invariants.toml row"
        );
    }
    let evidence =
        std::fs::read_to_string(repo_root().join("registries/evidence.toml")).expect("evidence");
    for id in &registry.registry.bound_evidence {
        assert!(
            evidence.contains(&format!("id = \"{id}\"")),
            "bound evidence {id} is not a live evidence.toml row"
        );
    }
    // Every asset's primary claim must resolve too.
    for asset in &registry.assets {
        let found = invariants.contains(&format!("id = \"{}\"", asset.primary_claim_ref))
            || evidence.contains(&format!("id = \"{}\"", asset.primary_claim_ref));
        assert!(
            found,
            "asset {} names claim {} which resolves to no registry row",
            asset.id, asset.primary_claim_ref
        );
    }
}

#[test]
fn tm_checker_index_registers_every_threat_entrypoint() {
    let index = std::fs::read_to_string(repo_root().join("registries/checker_index.toml"))
        .expect("checker_index");
    for symbol in ["threat_model", "threat_registry_source", "g0_threat_e2e"] {
        assert!(
            index.contains(&format!("symbol = \"{symbol}\"")),
            "checker_index.toml is missing a row for {symbol}"
        );
    }
}
