//! Typed mutation, derivation, and property suite for the frozen workspace
//! topology (fgdb-g0-workspace-topology-1q9m).
//!
//! Four kinds of test live here, and the distinction matters:
//!
//!   * **Derivation tests** prove the crate universe, the inventory partition,
//!     and the donor bijection are computed FROM the frozen plan blocks rather
//!     than retyped next to them.
//!   * **Registry mutation fixtures** take the frozen registry, break exactly
//!     one thing, and assert the checker reports the exact violation code. A
//!     checker nobody has watched go red is a checker nobody knows works.
//!   * **Synthetic-graph property tests** exercise the laws that CANNOT fire
//!     against today's tree, because the crates they govern do not exist yet:
//!     posture closures, crate-graph cycles, layer inversion. Without these the
//!     green bar would be reporting "no composition crate is active", which
//!     reads exactly like "no composition crate is misplaced".
//!   * **Scanner tests** pin the manifest reader's subset and its fail-closed
//!     behaviour, because a scanner that silently skips what it does not
//!     understand turns every closed-universe law into a suggestion.
//!
//! The hash pins are duplicated here on purpose. `topology-check` recomputes
//! them from the registry it just read, so a coordinated edit of rows AND
//! header keeps the binary green; a constant in a test file does not move
//! unless someone moves it.

use registry_check::topology::{
    self, AssetEvidenceGap, Capability, ManifestDependency, ScannedCrate, TopologyRegistry,
    WorkspaceScan, crate_graph_cycle, decompose_inventory, design_bijection, load_from_repo,
    parse_layer_table, posture_closures, recompute_id_table_hash, recompute_semantic_contract_hash,
    required_edge_coverage, required_edge_floor_violations, scan_manifest, scan_workspace,
    source_block_text, validate_topology,
};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

const ID_TABLE_PIN: &str = "fnv1a64:b422bc59c3da23ca";
// Re-frozen on each crate activation (fgdb-reference 08bfadf, fgdb-sim,
// fgdb-strata, then fgdb by fgdb-j0vu). Derived from the gate's own drift
// message, never hand-computed. The semantic contract covers activation_status
// AND posture status, so activating a crate MUST move this — a pin that
// survived the change would be pinning nothing.
const SEMANTIC_CONTRACT_PIN: &str = "fnv1a64:b87cb355fab8bcd8";

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace root")
        .to_path_buf()
}

fn registry() -> TopologyRegistry {
    load_from_repo(&repo_root()).expect("workspace_topology.toml loads")
}

fn registry_text() -> String {
    std::fs::read_to_string(repo_root().join(topology::REGISTRY_PATH))
        .expect("read workspace_topology.toml")
}

fn block_text(id: &str) -> String {
    let registry = registry();
    let block = registry.source_block(id).expect("source block exists");
    source_block_text(block, &repo_root()).expect("block reads")
}

/// Apply one textual mutation and return the violation codes it produces.
/// Panics if the mutation did not apply — a fixture that silently no-ops is a
/// fixture that passes for the wrong reason.
fn codes_after(original: &str, replacement: &str) -> Vec<String> {
    codes_after_all(&[(original, replacement)])
}

fn codes_after_all(edits: &[(&str, &str)]) -> Vec<String> {
    let mut text = registry_text();
    for (original, replacement) in edits {
        assert_eq!(
            text.matches(original).count(),
            1,
            "mutation anchor {original:?} must occur exactly once"
        );
        text = text.replacen(original, replacement, 1);
    }
    let mutated = topology::parse_topology(&text).expect("mutated registry still parses");
    let mut codes: Vec<String> = validate_topology(&mutated, &repo_root())
        .into_iter()
        .map(|violation| violation.code)
        .collect();
    codes.sort();
    codes.dedup();
    codes
}

fn assert_reports(codes: &[String], expected: &str) {
    assert!(
        codes.iter().any(|code| code == expected),
        "expected violation {expected:?}, got {codes:?}"
    );
}

// -----------------------------------------------------------------------------
// The frozen registry itself
// -----------------------------------------------------------------------------

#[test]
fn topology_registry_validates_clean() {
    let violations = validate_topology(&registry(), &repo_root());
    assert!(
        violations.is_empty(),
        "the frozen topology must validate clean: {violations:#?}"
    );
}

#[test]
fn topology_document_is_the_regenerated_bytes() {
    assert!(
        topology::check_document(&registry(), &repo_root()).expect("document generates"),
        "docs/WORKSPACE_TOPOLOGY.md is not the regenerated bytes; run topology-check --write"
    );
}

#[test]
fn topology_document_generation_is_deterministic() {
    let registry = registry();
    let first = topology::generate_document(&registry, &repo_root()).expect("first");
    let second = topology::generate_document(&registry, &repo_root()).expect("second");
    assert_eq!(first, second);
}

#[test]
fn topology_id_table_hash_pin() {
    let registry = registry();
    assert_eq!(recompute_id_table_hash(&registry), ID_TABLE_PIN);
    assert_eq!(registry.registry.id_table_hash, ID_TABLE_PIN);
}

#[test]
fn topology_semantic_contract_hash_pin() {
    let registry = registry();
    assert_eq!(
        recompute_semantic_contract_hash(&registry),
        SEMANTIC_CONTRACT_PIN
    );
    assert_eq!(
        registry.registry.semantic_contract_hash,
        SEMANTIC_CONTRACT_PIN
    );
}

#[test]
fn topology_cardinalities_are_exactly_the_plan_enumeration() {
    let registry = registry();
    assert_eq!(registry.layers.len(), 14, "§18.1 has fourteen layers");
    assert_eq!(
        registry.crates.len(),
        70,
        "sixty-nine crates plus fgdb-shard"
    );
    assert_eq!(registry.capabilities.len(), 51, "23 + 19 + 9");
    assert_eq!(registry.postures.len(), 3, "§1 constraint 5");
    assert_eq!(registry.foundation_projects.len(), 3);
    assert_eq!(
        registry
            .crates
            .iter()
            .filter(|row| row.activation_status == "active")
            .count(),
        19,
        "sixteen ordinary crates (fgdb-crypto by fgdb-w1-crypto-y5o's BLAKE3/AEAD \
         kernel, fgdb-chronicle by fgdb-w2-object-identity-t0f's §5.1 identity \
         pipeline, fgdb-reference by fgdb-w2-delta-batches-og6n's semantics \
         oracle, fgdb-sim by fgdb-verif-sim-q97e's durability/semantics \
         differential, fgdb-strata by fgdb-w3-tier-d-ctj's tier-one \
         delta-block format, and fgdb itself by fgdb-j0vu's end-to-end spine — \
         the first COMPOSITION-layer crate to activate, which is also what turns \
         the embedded posture from deferred to live) plus all three landed \
         islands: fgdb-unsafe-simd, fgdb-unsafe-arena and fgdb-unsafe-vfs"
    );
    assert_eq!(
        registry
            .crates
            .iter()
            .filter(|row| row.unsafe_policy == "deny_ledgered")
            .count(),
        3,
        "exactly the three named unsafe islands"
    );
}

// -----------------------------------------------------------------------------
// Derivation: the map is computed from the plan, not typed beside it
// -----------------------------------------------------------------------------

#[test]
fn topology_crate_universe_is_derived_from_the_frozen_table() {
    let registry = registry();
    let parsed = parse_layer_table(&block_text("plan-crate-layer-table-v1")).expect("table parses");
    assert_eq!(parsed.len(), registry.layers.len());
    let declared: BTreeSet<&str> = registry
        .crates
        .iter()
        .map(|row| row.name.as_str())
        .collect();
    let spelled: BTreeSet<&str> = parsed
        .iter()
        .flat_map(|row| row.tokens.iter().map(String::as_str))
        .collect();
    assert!(
        spelled.difference(&declared).next().is_none(),
        "the plan spells crates the registry does not declare: {:?}",
        spelled.difference(&declared).collect::<Vec<_>>()
    );
    assert_eq!(
        spelled.len(),
        declared.len(),
        "every declared crate must be spelled by the frozen table"
    );
}

#[test]
fn topology_layer_table_parser_keeps_source_order_and_drops_cross_references() {
    let parsed = parse_layer_table(&block_text("plan-crate-layer-table-v1")).expect("parses");
    let loom = parsed
        .iter()
        .find(|row| row.title == "Loom")
        .expect("Loom row");
    // The Loom row's annotation cross-references a Txn crate. The parser keeps
    // the token (coverage) and the membership law filters it by layer — which is
    // the whole reason membership is checked per-layer rather than per-token.
    assert!(loom.tokens.contains(&"fgdb-secure-view".to_string()));
    assert_eq!(
        loom.tokens.first().map(String::as_str),
        Some("fgdb-gql"),
        "source order, not alphabetical: the census sorts, the source spells"
    );
    let aegis = parsed
        .iter()
        .find(|row| row.title == "Aegis")
        .expect("Aegis row");
    assert!(aegis.tokens.contains(&"fgdb-order".to_string()));
    assert!(aegis.tokens.contains(&"fgdb-shard".to_string()));
}

#[test]
fn topology_inventory_residue_is_punctuation_only() {
    let registry = registry();
    let line = block_text("plan-build-inventory-v1");
    let coverage = decompose_inventory(line.trim_end_matches('\n'), &registry);
    assert!(
        coverage.unresolved.is_empty(),
        "every phrase must resolve exactly once: {:?}",
        coverage.unresolved
    );
    assert!(
        coverage.illegal_residue.is_empty(),
        "§18.2 names something the registry does not: {:?} / {:?}",
        coverage.illegal_residue,
        coverage.residue
    );
}

#[test]
fn topology_inventory_coverage_catches_a_dropped_capability() {
    let mut registry = registry();
    let dropped = registry
        .capabilities
        .iter()
        .position(|row| row.id == "persistent-union-find")
        .expect("row exists");
    let removed = registry.capabilities.remove(dropped);
    let line = block_text("plan-build-inventory-v1");
    let coverage = decompose_inventory(line.trim_end_matches('\n'), &registry);
    assert!(
        !coverage.illegal_residue.is_empty(),
        "dropping {:?} must leave residue; otherwise coverage proves nothing",
        removed.source_phrase
    );
    assert!(coverage.residue.contains("persistent union-find"));
}

#[test]
fn topology_design_bijection_is_total() {
    let registry = registry();
    let violations = design_bijection(&block_text("plan-frankensqlite-donor-v1"), &registry);
    assert!(violations.is_empty(), "{violations:#?}");
}

#[test]
fn topology_design_bijection_catches_a_double_claim() {
    let mut registry = registry();
    let phrase = registry
        .capabilities
        .iter()
        .find(|row| row.id == "design-encryption")
        .expect("row")
        .source_phrase
        .clone();
    if let Some(row) = registry
        .capabilities
        .iter_mut()
        .find(|row| row.id == "design-time-travel")
    {
        row.source_phrase = phrase;
    }
    let codes: Vec<String> =
        design_bijection(&block_text("plan-frankensqlite-donor-v1"), &registry)
            .into_iter()
            .map(|violation| violation.code)
            .collect();
    assert!(
        codes.contains(&"design_row_double_claim".to_string())
            || codes.contains(&"design_row_unclaimed".to_string()),
        "{codes:?}"
    );
}

#[test]
fn topology_consume_rows_carry_resolvable_asset_evidence() {
    let registry = registry();
    let asupersync = block_text("plan-asupersync-assets-v1");
    let fnx = block_text("plan-fnx-assets-v1");
    for capability in registry
        .capabilities
        .iter()
        .filter(|row| row.disposition == "consume_from")
    {
        if registry
            .asset_evidence_gaps
            .iter()
            .any(|gap| gap.capability_id == capability.id)
        {
            continue;
        }
        let block = match capability.foundation_project.as_str() {
            "asupersync" => &asupersync,
            "franken_networkx" => &fnx,
            other => panic!("unexpected foundation project {other:?}"),
        };
        let hits = block
            .lines()
            .filter(|line| line.contains(&capability.foundation_asset))
            .count();
        assert_eq!(hits, 1, "{} asset evidence must be exact", capability.id);
    }
}

#[test]
fn topology_asset_evidence_gap_is_a_verified_absence() {
    let registry = registry();
    assert_eq!(registry.asset_evidence_gaps.len(), 1);
    let gap = &registry.asset_evidence_gaps[0];
    assert_eq!(gap.capability_id, "queue-clients");
    let block = block_text(&gap.verified_absent_from);
    let capability = registry
        .capabilities
        .iter()
        .find(|row| row.id == gap.capability_id)
        .expect("capability");
    assert!(
        !block.contains(&capability.source_phrase),
        "the gap is only legal while the asset row really is absent"
    );
    assert!(capability.foundation_asset.is_empty());
}

#[test]
fn topology_workstream_titles_are_verbatim_from_the_plan() {
    let registry = registry();
    let block = block_text("plan-workstream-table-v1");
    for scope in registry
        .owner_scopes
        .iter()
        .filter(|scope| scope.kind == "workstream")
    {
        assert!(
            block.contains(&format!("| {} | {} |", scope.id, scope.title)),
            "{} title is not verbatim in §19",
            scope.id
        );
    }
}

#[test]
fn topology_island_roster_agrees_with_the_unsafe_boundary_ledger() {
    let registry = registry();
    let mut violations = Vec::new();
    topology::check_island_roster(&registry, &repo_root(), &mut violations);
    assert!(violations.is_empty(), "{violations:#?}");
    // And the bijection is over a non-empty set, so the agreement is not the
    // agreement of two empty lists.
    assert_eq!(registry.layer_crates("unsafe_islands").len(), 3);
}

#[test]
fn topology_neg_island_status_disagreement() {
    // The two registries must agree about every island, and the fixture has to
    // follow the tree rather than the other way round. It used to flip
    // `fgdb-unsafe-vfs` from planned to active while the ledger still rostered
    // it planned; all three islands have now landed, so the disagreement is
    // seeded in the other direction — the topology calls the island planned
    // while the ledger rosters it `present`. Either way round is the same law:
    // a half-move fails loudly in both files.
    let codes = codes_after(
        "name = \"fgdb-unsafe-vfs\"\nlayer = \"unsafe_islands\"\nlayer_position = 3\nrole = \"Raw file/mapping syscall surfaces beneath the filesystem-profile layer.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"deny_ledgered\"\nactivation_status = \"active\"",
        "name = \"fgdb-unsafe-vfs\"\nlayer = \"unsafe_islands\"\nlayer_position = 3\nrole = \"Raw file/mapping syscall surfaces beneath the filesystem-profile layer.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"deny_ledgered\"\nactivation_status = \"planned\"",
    );
    assert_reports(&codes, "island_status_disagreement");
}

#[test]
fn topology_neg_island_dropped_from_the_layer() {
    let codes = codes_after(
        "name = \"fgdb-unsafe-simd\"\nlayer = \"unsafe_islands\"\nlayer_position = 1",
        "name = \"fgdb-unsafe-simd-x\"\nlayer = \"unsafe_islands\"\nlayer_position = 1",
    );
    assert_reports(&codes, "island_roster_extra");
    assert_reports(&codes, "island_roster_missing");
}

// -----------------------------------------------------------------------------
// Mutation fixtures — every law watched going red
// -----------------------------------------------------------------------------

#[test]
fn topology_neg_dropped_crate_row() {
    let codes = codes_after(
        "[[crate]]\nname = \"fgdb-scratch\"\nlayer = \"strata\"\nlayer_position = 4\n",
        "[[crate]]\nname = \"fgdb-scratch-typo\"\nlayer = \"strata\"\nlayer_position = 4\n",
    );
    assert_reports(&codes, "crate_unregistered");
    assert_reports(&codes, "layer_membership_drift");
}

#[test]
fn topology_neg_crate_in_the_wrong_layer() {
    let codes = codes_after_all(&[
        (
            "name = \"fgdb-btree\"\nlayer = \"beacon\"\nlayer_position = 2",
            "name = \"fgdb-btree\"\nlayer = \"strata\"\nlayer_position = 5",
        ),
        ("layer_count = 14", "layer_count = 14"),
    ]);
    assert_reports(&codes, "layer_membership_drift");
}

#[test]
fn topology_neg_layer_membership_reordered() {
    let codes = codes_after_all(&[
        (
            "name = \"fgdb-props\"\nlayer = \"strata\"\nlayer_position = 2",
            "name = \"fgdb-props\"\nlayer = \"strata\"\nlayer_position = 3",
        ),
        (
            "name = \"fgdb-buffer\"\nlayer = \"strata\"\nlayer_position = 3",
            "name = \"fgdb-buffer\"\nlayer = \"strata\"\nlayer_position = 2",
        ),
    ]);
    assert_reports(&codes, "layer_membership_drift");
}

#[test]
fn topology_neg_layer_allowed_edges_widened() {
    let codes = codes_after(
        "id = \"foundation\"\ntitle = \"Foundation\"\nsource_order = 1\nallowed_outgoing_layers = [\"foundation\", \"unsafe_islands\"]",
        "id = \"foundation\"\ntitle = \"Foundation\"\nsource_order = 1\nallowed_outgoing_layers = [\"foundation\", \"unsafe_islands\", \"chronicle\"]",
    );
    assert_reports(&codes, "layer_allowed_edges_drift");
}

#[test]
fn topology_neg_layer_title_renamed() {
    let codes = codes_after("title = \"Surface/operations\"", "title = \"Surface\"");
    assert_reports(&codes, "layer_titles_drift");
}

#[test]
fn topology_neg_ordinary_crate_relaxes_unsafe() {
    let codes = codes_after(
        "name = \"fgdb-codec\"\nlayer = \"foundation\"\nlayer_position = 8\nrole = \"In-house compression kernels for the registered durable codec layer.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"forbid\"",
        "name = \"fgdb-codec\"\nlayer = \"foundation\"\nlayer_position = 8\nrole = \"In-house compression kernels for the registered durable codec layer.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"deny_ledgered\"",
    );
    assert_reports(&codes, "unsafe_policy_relaxed");
}

#[test]
fn topology_neg_island_policy_downgraded() {
    let codes = codes_after(
        "name = \"fgdb-unsafe-arena\"\nlayer = \"unsafe_islands\"\nlayer_position = 2\nrole = \"Bump/region arena internals and generational-handle plumbing behind safe APIs.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"deny_ledgered\"",
        "name = \"fgdb-unsafe-arena\"\nlayer = \"unsafe_islands\"\nlayer_position = 2\nrole = \"Bump/region arena internals and generational-handle plumbing behind safe APIs.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"forbid\"",
    );
    assert_reports(&codes, "island_policy_drift");
}

#[test]
fn topology_neg_planned_crate_claims_a_directory() {
    // Keyed to fgdb-txn, not fgdb-strata: this fixture needs a crate that is
    // STILL planned, and strata was activated. Whoever activates fgdb-txn must
    // repoint it again rather than delete the law — a negative test whose subject
    // became legal stops testing without ever going red on its own.
    let codes = codes_after(
        "name = \"fgdb-txn\"\nlayer = \"txn_secure_access\"\nlayer_position = 1\nrole = \"MVCC, Graph-SSI/witness lifecycle, coordinator, final-effect merge ladder\"\nrole_basis = \"plan_parenthetical\"\nunsafe_policy = \"forbid\"\nactivation_status = \"planned\"\nposture_participation = \"all\"\nposture_basis = \"product_shape\"\nowner = \"W4\"\nowner_bead = \"fgdb-w4-g1-txn-core-qpmg\"\nmanifest_dir = \"\"",
        "name = \"fgdb-txn\"\nlayer = \"txn_secure_access\"\nlayer_position = 1\nrole = \"MVCC, Graph-SSI/witness lifecycle, coordinator, final-effect merge ladder\"\nrole_basis = \"plan_parenthetical\"\nunsafe_policy = \"forbid\"\nactivation_status = \"planned\"\nposture_participation = \"all\"\nposture_basis = \"product_shape\"\nowner = \"W4\"\nowner_bead = \"fgdb-w4-g1-txn-core-qpmg\"\nmanifest_dir = \"crates/fgdb-txn\"",
    );
    assert_reports(&codes, "inactive_with_manifest_dir");
}

#[test]
fn topology_neg_active_crate_loses_its_manifest_dir() {
    let codes = codes_after(
        "owner_bead = \"fgdb-w1-collections-lcg\"\nmanifest_dir = \"crates/fgdb-collections\"",
        "owner_bead = \"fgdb-w1-collections-lcg\"\nmanifest_dir = \"\"",
    );
    assert_reports(&codes, "active_without_manifest_dir");
    assert_reports(&codes, "member_unregistered");
}

/// The other direction of law 2: a crate that exists on disk but whose row says
/// it does not. This is the shape a "let me just scaffold the crate early" diff
/// takes, and it must not read as ordinary progress.
#[test]
fn topology_neg_live_crate_declared_planned() {
    let codes = codes_after(
        "activation_status = \"active\"\nposture_participation = \"all\"\nposture_basis = \"product_shape\"\nowner = \"W1\"\nowner_bead = \"fgdb-w1-collections-lcg\"\nmanifest_dir = \"crates/fgdb-collections\"",
        "activation_status = \"planned\"\nposture_participation = \"all\"\nposture_basis = \"product_shape\"\nowner = \"W1\"\nowner_bead = \"fgdb-w1-collections-lcg\"\nmanifest_dir = \"\"",
    );
    assert_reports(&codes, "phantom_crate_directory");
    assert_reports(&codes, "member_unregistered");
    assert_reports(&codes, "count_drift");
}

#[test]
fn topology_neg_foundation_revision_drift() {
    let codes = codes_after(
        "pinned_rev = \"3b34c9b0a14c55eb814cf4aaeceeba3be0c0a72e\"",
        "pinned_rev = \"0000000000000000000000000000000000000000\"",
    );
    assert_reports(&codes, "foundation_rev_drift");
}

#[test]
fn topology_neg_default_feature_escape_law_disabled() {
    // Turning the law off must not be silent: the pins move, which is the only
    // reason a policy column is worth having.
    let codes = codes_after(
        "default_features_must_be_disabled = true\ndefault_features_basis = \"workspace_convention_unanimous\"",
        "default_features_must_be_disabled = false\ndefault_features_basis = \"workspace_convention_unanimous\"",
    );
    assert_reports(&codes, "semantic_contract_hash_drift");
}

#[test]
fn topology_neg_forbidden_prefix_removed() {
    let codes = codes_after("package_prefix = \"fsqlite-\"", "package_prefix = \"fsq-\"");
    assert_reports(&codes, "semantic_contract_hash_drift");
}

#[test]
fn topology_neg_role_not_verbatim() {
    let codes = codes_after(
        "role = \"capsule/marker/logical-local roots, allocator, outcomes, checkpoints/retention, recovery/GC/scrub\"",
        "role = \"capsule and marker roots, allocator, outcomes, checkpoints, recovery\"",
    );
    assert_reports(&codes, "role_not_verbatim");
}

#[test]
fn topology_neg_source_block_byte_count() {
    let codes = codes_after("byte_count = 2642", "byte_count = 2643");
    assert_reports(&codes, "source_block_drift");
}

#[test]
fn topology_neg_capability_owner_removed() {
    let codes = codes_after(
        "id = \"btree\"\ndisposition = \"build_here\"\nsource_phrase = \"B-tree\"\nowner_crate = \"fgdb-btree\"",
        "id = \"btree\"\ndisposition = \"build_here\"\nsource_phrase = \"B-tree\"\nowner_crate = \"\"",
    );
    assert_reports(&codes, "build_here_without_owner");
}

#[test]
fn topology_neg_consumed_capability_claims_an_owner_crate() {
    let codes = codes_after(
        "id = \"raptorq\"\ndisposition = \"consume_from\"\nsource_phrase = \"RaptorQ\"\nowner_crate = \"\"",
        "id = \"raptorq\"\ndisposition = \"consume_from\"\nsource_phrase = \"RaptorQ\"\nowner_crate = \"fgdb-codec\"",
    );
    assert_reports(&codes, "consume_from_with_owner");
}

#[test]
fn topology_neg_stale_asset_evidence_gap() {
    let codes = codes_after(
        "capability_id = \"queue-clients\"\nverified_absent_from = \"plan-asupersync-assets-v1\"",
        "capability_id = \"raptorq\"\nverified_absent_from = \"plan-asupersync-assets-v1\"",
    );
    assert_reports(&codes, "asset_gap_resolvable");
}

#[test]
fn topology_neg_residue_allowance_widened_to_hide_a_capability() {
    let codes = codes_after(
        "text = \"The closed-universe constraint, which sounds like an albatross, is the moat: the entire dependency surface is auditable, deterministic under lab, and owned.\"",
        "text = \"tokenizers, CSV/JSONL/Parquet-lite readers\"",
    );
    assert_reports(&codes, "capability_phrase_unresolved");
}

#[test]
fn topology_neg_posture_entry_participation_drift() {
    let codes = codes_after(
        "name = \"fgdb-cli\"\nlayer = \"composition\"\nlayer_position = 3\nrole = \"The CLI binary with robot mode and a human mode.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"forbid\"\nactivation_status = \"planned\"\nposture_participation = \"entry_cli\"",
        "name = \"fgdb-cli\"\nlayer = \"composition\"\nlayer_position = 3\nrole = \"The CLI binary with robot mode and a human mode.\"\nrole_basis = \"layer_charter\"\nunsafe_policy = \"forbid\"\nactivation_status = \"planned\"\nposture_participation = \"all\"",
    );
    assert_reports(&codes, "posture_entry_participation_drift");
}

#[test]
fn topology_neg_owner_scope_unresolved() {
    let codes = codes_after(
        "owner = \"W11\"\nowner_bead = \"\"\nmanifest_dir = \"\"\n\n# Named by §18.1",
        "owner = \"W13\"\nowner_bead = \"\"\nmanifest_dir = \"\"\n\n# Named by §18.1",
    );
    assert_reports(&codes, "crate_owner_unresolved");
}

#[test]
fn topology_neg_tooling_member_deregistered() {
    // Dropping the registration does not make the member vanish: it becomes an
    // undeclared crate, which is exactly the diagnostic a new unregistered
    // workspace member should produce.
    let codes = codes_after(
        "tooling_members = [\"tools/registry-check\"]",
        "tooling_members = []",
    );
    assert_reports(&codes, "member_unregistered");
    assert_reports(&codes, "crate_undeclared");
}

#[test]
fn topology_neg_tooling_member_points_nowhere() {
    let codes = codes_after(
        "tooling_members = [\"tools/registry-check\"]",
        "tooling_members = [\"tools/registry-check\", \"tools/does-not-exist\"]",
    );
    assert_reports(&codes, "tooling_member_missing");
}

#[test]
fn topology_neg_count_drift() {
    let codes = codes_after("crate_count = 70", "crate_count = 69");
    assert_reports(&codes, "count_drift");
}

#[test]
fn topology_neg_acyclicity_law_disabled() {
    let codes = codes_after(
        "crate_graph_must_be_acyclic = true",
        "crate_graph_must_be_acyclic = false",
    );
    assert_reports(&codes, "acyclicity_disabled");
}

// -----------------------------------------------------------------------------
// Synthetic-graph properties — the laws today's tree cannot exercise
// -----------------------------------------------------------------------------

fn synthetic_crate(name: &str, deps: &[&str]) -> ScannedCrate {
    ScannedCrate {
        dir: format!("crates/{name}"),
        package_name: name.to_string(),
        dependencies: deps
            .iter()
            .map(|dep| ManifestDependency {
                key: (*dep).to_string(),
                package: (*dep).to_string(),
                table: "dependencies".to_string(),
                path: format!("../{dep}"),
                git: String::new(),
                rev: String::new(),
                default_features_disabled: false,
            })
            .collect(),
        lints_workspace: true,
        root_path: "src/lib.rs".to_string(),
        root_forbids_unsafe: true,
        root_denies_unsafe: false,
        relaxes_unsafe: false,
    }
}

fn synthetic_scan(crates: Vec<ScannedCrate>) -> WorkspaceScan {
    WorkspaceScan {
        members: crates.iter().map(|entry| entry.dir.clone()).collect(),
        workspace_unsafe_lint: "forbid".to_string(),
        toolchain_channel: "nightly-2026-07-05".to_string(),
        crates,
    }
}

#[test]
fn topology_posture_closure_rejects_a_test_only_crate() {
    let registry = registry();
    // The law that cannot fire today: no composition crate is active, so the
    // real tree reports `deferred` for all three postures. Hand the evaluator
    // the graph the law exists to reject.
    let scan = synthetic_scan(vec![
        synthetic_crate("fgdb", &["fgdb-types", "fgdb-bench"]),
        synthetic_crate("fgdb-types", &[]),
        synthetic_crate("fgdb-bench", &[]),
    ]);
    let closures = posture_closures(&registry, &scan);
    let embedded = closures
        .iter()
        .find(|closure| closure.posture_id == "embedded")
        .expect("embedded posture");
    assert_eq!(embedded.status, "live");
    assert_eq!(embedded.illegal, vec!["fgdb-bench".to_string()]);
    let server = closures
        .iter()
        .find(|closure| closure.posture_id == "server")
        .expect("server posture");
    assert_eq!(server.status, "deferred", "no fgdb-server in this graph");
}

#[test]
fn topology_posture_closure_accepts_an_engine_only_closure() {
    let registry = registry();
    let scan = synthetic_scan(vec![
        synthetic_crate("fgdb", &["fgdb-txn"]),
        synthetic_crate("fgdb-txn", &["fgdb-strata"]),
        synthetic_crate("fgdb-strata", &[]),
    ]);
    let embedded = posture_closures(&registry, &scan)
        .into_iter()
        .find(|closure| closure.posture_id == "embedded")
        .expect("embedded posture");
    assert!(embedded.illegal.is_empty(), "{embedded:?}");
    assert_eq!(embedded.closure.len(), 3);
}

#[test]
fn topology_posture_closure_rejects_a_foreign_entry_crate() {
    let registry = registry();
    let scan = synthetic_scan(vec![
        synthetic_crate("fgdb-server", &["fgdb"]),
        synthetic_crate("fgdb", &[]),
    ]);
    let server = posture_closures(&registry, &scan)
        .into_iter()
        .find(|closure| closure.posture_id == "server")
        .expect("server posture");
    assert_eq!(
        server.illegal,
        vec!["fgdb".to_string()],
        "one posture's entry crate is not another posture's library"
    );
}

#[test]
fn topology_crate_graph_cycle_detection() {
    let acyclic = synthetic_scan(vec![
        synthetic_crate("fgdb-a", &["fgdb-b"]),
        synthetic_crate("fgdb-b", &["fgdb-c"]),
        synthetic_crate("fgdb-c", &[]),
    ]);
    assert!(crate_graph_cycle(&acyclic).is_empty());
    let cyclic = synthetic_scan(vec![
        synthetic_crate("fgdb-a", &["fgdb-b"]),
        synthetic_crate("fgdb-b", &["fgdb-c"]),
        synthetic_crate("fgdb-c", &["fgdb-a"]),
    ]);
    let cycle = crate_graph_cycle(&cyclic);
    assert_eq!(cycle.len(), 3, "{cycle:?}");
}

#[test]
fn topology_required_edges_report_deferred_not_pass() {
    let registry = registry();
    let scan = scan_workspace(&repo_root()).expect("workspace scans");
    let coverage = required_edge_coverage(&registry, &scan);
    assert_eq!(
        (
            coverage.declared,
            coverage.evaluated_live,
            coverage.deferred,
            coverage.ratcheted_live_floor,
            coverage.unratcheted_live,
        ),
        (8, 1, 7, 1, 0),
        "the full named-edge population and its ratcheted partition"
    );
    let live: Vec<&str> = coverage
        .statuses
        .iter()
        .filter(|status| status.status != "deferred")
        .map(|status| status.id.as_str())
        .collect();
    // Exactly one named edge has both endpoints active today. If this number
    // ever silently drops to zero the law is vacuous, and the suite says so.
    assert_eq!(
        live,
        vec!["calibrate-over-asupersync"],
        "the live/deferred split is part of the contract"
    );
    assert!(
        coverage
            .statuses
            .iter()
            .all(|status| status.status != "fail"),
        "{:#?}",
        coverage.statuses
    );
}

#[test]
fn topology_required_edge_floor_allows_forward_and_rejects_backward() {
    let base = registry();

    // FORWARD: 1 -> 2 evaluated edges is legal while the monotone floor stays
    // at the one edge this commit owns. A floor is a lower bound, not a global
    // equality over a graph another pane may advance.
    let mut forward = base.clone();
    forward
        .crates
        .iter_mut()
        .find(|row| row.name == "fgdb-prism")
        .expect("fgdb-prism row")
        .activation_status = "active".into();
    let forward_scan = synthetic_scan(vec![
        synthetic_crate("fgdb-calibrate", &["asupersync"]),
        synthetic_crate("fgdb-prism", &["fnx-core"]),
    ]);
    let forward_coverage = required_edge_coverage(&forward, &forward_scan);
    assert_eq!(
        (
            forward_coverage.declared,
            forward_coverage.evaluated_live,
            forward_coverage.deferred,
            forward_coverage.ratcheted_live_floor,
            forward_coverage.unratcheted_live,
        ),
        (8, 2, 6, 1, 1),
        "named forward mutation: 1 -> 2 evaluated, 7 -> 6 deferred"
    );
    assert!(
        required_edge_floor_violations(&forward, &forward_coverage).is_empty(),
        "forward progress above a set-floor must remain legal"
    );

    // BACKWARD: 1 -> 0 is rejected because the exact floor member, not merely
    // the aggregate count, moved back to deferred.
    let mut backward = base.clone();
    backward
        .crates
        .iter_mut()
        .find(|row| row.name == "fgdb-calibrate")
        .expect("fgdb-calibrate row")
        .activation_status = "planned".into();
    let backward_coverage = required_edge_coverage(&backward, &synthetic_scan(Vec::new()));
    assert_eq!(
        (
            backward_coverage.declared,
            backward_coverage.evaluated_live,
            backward_coverage.deferred,
        ),
        (8, 0, 8),
        "named backward mutation: 1 -> 0 evaluated, 7 -> 8 deferred"
    );
    let backward_codes: BTreeSet<String> =
        required_edge_floor_violations(&backward, &backward_coverage)
            .into_iter()
            .map(|violation| violation.code)
            .collect();
    assert!(
        backward_codes.contains("required_edge_floor_regression"),
        "the backward control must fire: {backward_codes:?}"
    );

    // BYPASS CONTROL: the old aggregate literal accepted a one-for-one swap.
    // Keep Prism live while re-deferring calibrate; the total remains one, but
    // the set-floor still rejects the exact regression.
    let mut substitution = forward;
    substitution
        .crates
        .iter_mut()
        .find(|row| row.name == "fgdb-calibrate")
        .expect("fgdb-calibrate row")
        .activation_status = "planned".into();
    let substitution_scan = synthetic_scan(vec![synthetic_crate("fgdb-prism", &["fnx-core"])]);
    let substitution_coverage = required_edge_coverage(&substitution, &substitution_scan);
    assert_eq!(
        substitution_coverage.evaluated_live, 1,
        "the aggregate stays at one"
    );
    assert!(
        required_edge_floor_violations(&substitution, &substitution_coverage)
            .iter()
            .any(|violation| violation.code == "required_edge_floor_regression"),
        "one live edge may not substitute for the ratcheted edge"
    );

    // VACUITY CONTROL: an empty set-floor would reject nothing, so it is itself
    // a violation. This control must fire independently of the backward case.
    let mut vacuous = base;
    vacuous.registry.required_dependency_live_floor.clear();
    let vacuous_scan = scan_workspace(&repo_root()).expect("workspace scans");
    let vacuous_coverage = required_edge_coverage(&vacuous, &vacuous_scan);
    assert!(
        required_edge_floor_violations(&vacuous, &vacuous_coverage)
            .iter()
            .any(|violation| violation.code == "required_edge_floor_vacuous"),
        "the empty-floor control must fire"
    );
}

// -----------------------------------------------------------------------------
// The manifest scanner
// -----------------------------------------------------------------------------

#[test]
fn topology_manifest_scanner_reads_the_declared_subset() {
    let text = r#"
[package]
name = "fgdb-example"
version = "0.0.1"

[lints]
workspace = true

[dependencies]
asupersync = { git = "https://example/asupersync", rev = "abc", default-features = false }
fgdb-types = { path = "../fgdb-types" }
renamed = { path = "../other", package = "fgdb-other" }

[dev-dependencies]
fnx-generators = { git = "https://example/fnx", rev = "def" }
"#;
    let scanned = scan_manifest("crates/fgdb-example", text).expect("scans");
    assert_eq!(scanned.package_name, "fgdb-example");
    assert!(scanned.lints_workspace);
    assert_eq!(scanned.dependencies.len(), 4);
    let asupersync = scanned
        .dependencies
        .iter()
        .find(|dependency| dependency.package == "asupersync")
        .expect("asupersync");
    assert_eq!(asupersync.table, "dependencies");
    assert_eq!(asupersync.rev, "abc");
    assert!(asupersync.default_features_disabled);
    let renamed = scanned
        .dependencies
        .iter()
        .find(|dependency| dependency.key == "renamed")
        .expect("renamed");
    assert_eq!(
        renamed.package, "fgdb-other",
        "the closed-universe law must see the REAL package name, not the rename"
    );
    let dev = scanned
        .dependencies
        .iter()
        .find(|dependency| dependency.package == "fnx-generators")
        .expect("dev dep");
    assert_eq!(dev.table, "dev-dependencies");
    assert!(!dev.default_features_disabled);
}

#[test]
fn topology_manifest_scanner_reads_the_sub_table_form() {
    let text = r#"
[package]
name = "fgdb-example"

[dependencies.asupersync]
git = "https://example/asupersync"
rev = "abc"
default-features = false
"#;
    let scanned = scan_manifest("crates/fgdb-example", text).expect("scans");
    assert_eq!(scanned.dependencies.len(), 1);
    assert_eq!(scanned.dependencies[0].package, "asupersync");
    assert!(scanned.dependencies[0].default_features_disabled);
}

#[test]
fn topology_manifest_scanner_fails_closed() {
    let unknown_field = r#"
[package]
name = "fgdb-example"

[dependencies]
mystery = { registry = "somewhere" }
"#;
    assert!(
        scan_manifest("crates/fgdb-example", unknown_field).is_err(),
        "a scanner that skips what it does not understand turns every law into a suggestion"
    );
    let no_package = "[dependencies]\nfgdb-types = { path = \"../fgdb-types\" }\n";
    assert!(scan_manifest("crates/fgdb-example", no_package).is_err());
}

#[test]
fn topology_manifest_scanner_ignores_comments_and_strings() {
    let text = "[package]\nname = \"fgdb-example\" # trailing comment\ndescription = \"a # inside a string\"\n";
    let scanned = scan_manifest("crates/fgdb-example", text).expect("scans");
    assert_eq!(scanned.package_name, "fgdb-example");
}

#[test]
fn topology_live_scan_matches_the_registry() {
    let registry = registry();
    let scan = scan_workspace(&repo_root()).expect("workspace scans");
    assert_eq!(scan.workspace_unsafe_lint, "forbid");
    assert_eq!(scan.toolchain_channel, registry.registry.toolchain_channel);
    let mut islands = 0_usize;
    for row in registry.active_crates() {
        let scanned = scan
            .by_dir(&row.manifest_dir)
            .unwrap_or_else(|| panic!("{} has no manifest", row.name));
        assert_eq!(scanned.package_name, row.name);
        // The policy column is a claim about the manifest AND the root, and the
        // two policies want OPPOSITE things of the manifest. An ordinary crate
        // inherits the workspace forbid and may never relax it. An island must
        // NOT inherit it -- `forbid` cannot be lowered, so inheriting it would
        // make every ledgered site uncompilable -- which leaves its own
        // `#![deny(unsafe_code)]` as the only thing constraining it, so that is
        // asserted positively rather than assumed from the column.
        if row.unsafe_policy == "deny_ledgered" {
            islands += 1;
            assert!(
                scanned.root_denies_unsafe,
                "{} is an island and its root must deny",
                row.name
            );
            assert!(
                !scanned.lints_workspace,
                "{} is an island and must not inherit the workspace forbid",
                row.name
            );
        } else {
            assert!(scanned.root_forbids_unsafe, "{} root", row.name);
            assert!(!scanned.relaxes_unsafe, "{} relaxes unsafe", row.name);
            assert!(
                scanned.lints_workspace,
                "{} must inherit the workspace forbid",
                row.name
            );
        }
    }
    assert!(
        islands > 0,
        "no island is active, so the island branch above asserted nothing"
    );
}

// -----------------------------------------------------------------------------
// Registration
// -----------------------------------------------------------------------------

#[test]
fn topology_checker_index_registers_every_entrypoint() {
    let index = std::fs::read_to_string(repo_root().join("registries/checker_index.toml"))
        .expect("checker_index");
    for symbol in [
        "workspace_topology",
        "topology_registry_source",
        "g0_topology_e2e",
    ] {
        assert!(
            index.contains(&format!("symbol = \"{symbol}\"")),
            "checker_index.toml is missing a row for {symbol}"
        );
    }
}

#[test]
fn topology_registry_is_registered_in_the_workspace_manifest() {
    let manifest = std::fs::read_to_string(repo_root().join("tools/registry-check/Cargo.toml"))
        .expect("registry-check manifest");
    assert!(manifest.contains("name = \"topology-check\""));
    let script = repo_root().join("scripts/g0_topology_e2e.sh");
    assert!(script.is_file(), "the E2E gate must ship with the checker");
}

/// A capability row and a gap row are the two halves of one claim; keep their
/// types linked so a refactor cannot silently split them.
#[test]
fn topology_gap_rows_reference_consumed_capabilities_only() {
    let registry = registry();
    for gap in &registry.asset_evidence_gaps {
        let capability: &Capability = registry
            .capabilities
            .iter()
            .find(|row| row.id == gap.capability_id)
            .expect("gap names a capability");
        assert_eq!(capability.disposition, "consume_from");
        let _typed: &AssetEvidenceGap = gap;
    }
}

// ---------------------------------------------------------------------------
// fgdb-fa3k — the crates → registries compile-time coupling is exactly one edge
// ---------------------------------------------------------------------------
//
// The catalog lane's scoping question ("may a registries-only increment skip
// the workspace test?") rests on ONE premise, proven by hand in the bead and
// made executable here: crates/** compiles registries/ content into itself at
// exactly one site, fgdb-types/src/refs.rs's include of
// logical_object_kinds.toml — so an increment touching any OTHER registry
// file cannot break a crate build, and one touching THAT projection can. If
// this guard ever goes red, the premise moved and any scoping rule derived
// from it must be re-derived, not trusted.

/// What an include site looks like to the guard.
#[derive(Debug, Clone, PartialEq, Eq)]
enum IncludeSite {
    /// A constant-string path the compiler and the guard both see exactly.
    Literal(String),
    /// A concat!/expression include: the compiler accepts it and no lexical
    /// scan can bind its value, so the guard refuses it outright rather than
    /// guess.
    Unverifiable,
}

/// Scan one source text for `include_bytes!`/`include_str!` sites whose body
/// mentions `registries/`. Deliberately lexical: the pattern set is the two
/// macro spellings, which are the only compile-time file-include macros the
/// toolchain accepts.
fn registry_include_sites(source: &str) -> Vec<IncludeSite> {
    fn classify(segment: &str) -> Option<IncludeSite> {
        let after_open = segment.trim_start().strip_prefix('(')?;
        let trimmed = after_open.trim_start();
        if let Some(lit) = trimmed.strip_prefix('"') {
            let end = lit.find('"')?;
            let literal = &lit[..end];
            return literal
                .contains("registries/")
                .then(|| IncludeSite::Literal(literal.to_string()));
        }
        // Not a bare literal. Only suspicious if the body mentions
        // registries at all — otherwise it is an ordinary computed include
        // and none of the guard's business.
        let body_end = trimmed.find(')').unwrap_or(trimmed.len()).min(512);
        trimmed[..body_end]
            .contains("registries/")
            .then_some(IncludeSite::Unverifiable)
    }

    let mut sites = Vec::new();
    for needle in ["include_bytes!", "include_str!"] {
        for segment in source.split(needle).skip(1) {
            if let Some(site) = classify(segment) {
                sites.push(site);
            }
        }
    }
    sites
}

#[test]
fn the_extractor_sees_literals_and_refuses_the_unverifiable() {
    // Direction one: a real citation is extracted — the exact refs.rs form.
    let real =
        r#"const R: &[u8] = include_bytes!("../../../registries/logical_object_kinds.toml");"#;
    assert_eq!(
        registry_include_sites(real),
        vec![IncludeSite::Literal(
            "../../../registries/logical_object_kinds.toml".to_string()
        )]
    );
    // Direction two: a concat! include mentioning registries/ is REFUSED as
    // unverifiable — never silently passed, never silently included.
    let computed = r#"include_str!(concat!("../../", "registries/x.toml"));"#;
    assert_eq!(
        registry_include_sites(computed),
        vec![IncludeSite::Unverifiable]
    );
    // Direction three: prose mentioning registries/ is not an include.
    assert_eq!(
        registry_include_sites("// read registries/laws.toml at runtime"),
        Vec::new()
    );
    // Whitespace variants are still literals.
    assert_eq!(
        registry_include_sites(r#"include_bytes!(  "../registries/y.toml" )"#),
        vec![IncludeSite::Literal("../registries/y.toml".to_string())]
    );
}

#[test]
fn crates_reach_registries_at_compile_time_through_exactly_one_edge() {
    fn walk(dir: &Path, files: &mut Vec<PathBuf>) {
        for entry in std::fs::read_dir(dir).expect("readable dir") {
            let path = entry.expect("dir entry").path();
            if path.is_dir() {
                walk(&path, files);
            } else if path.extension().is_some_and(|ext| ext == "rs") {
                files.push(path);
            }
        }
    }

    let root = repo_root();
    let mut sources = Vec::new();
    walk(&root.join("crates"), &mut sources);
    assert!(
        sources.len() > 20,
        "the sweep actually saw the crate universe ({} files)",
        sources.len()
    );

    let mut literals: Vec<(String, String)> = Vec::new();
    let mut unverifiable: Vec<String> = Vec::new();
    for path in &sources {
        let text = std::fs::read_to_string(path).expect("source reads");
        let rel = path
            .strip_prefix(&root)
            .expect("under root")
            .to_string_lossy()
            .replace('\\', "/");
        for site in registry_include_sites(&text) {
            match site {
                IncludeSite::Literal(target) => literals.push((rel.clone(), target)),
                IncludeSite::Unverifiable => unverifiable.push(rel.clone()),
            }
        }
    }

    assert_eq!(
        unverifiable,
        Vec::<String>::new(),
        "a concat!/expression include of registries/ cannot be statically \
         bound; make it a literal or remove it"
    );
    assert_eq!(
        literals,
        vec![(
            "crates/fgdb-types/src/refs.rs".to_string(),
            "../../../registries/logical_object_kinds.toml".to_string()
        )],
        "the compile-time coupling moved: re-derive the catalog-lane \
         scoping premise (fgdb-fa3k) before trusting any scoped test rule"
    );
}
