//! Oracle-verified AEAD vectors for the in-house (X)ChaCha20-Poly1305.
//!
//! PROVENANCE. The fixture module was GENERATED on 2026-07-29 by the dev-time
//! scratchpad oracle `aead_oracle` linking RustCrypto `chacha20poly1305` v0.10
//! (the audited implementation asupersync itself links). Inputs are
//! deterministic byte patterns: plaintext len N = (i+3)%251, AAD = (i+11)%251
//! (plain ChaCha vectors use +5/+23), key = 0x00..0x1f, nonces spelled in the
//! fixtures. The oracle is not a dependency of anything here; frozen goldens
//! only. A tag mismatch anywhere in the ChaCha20 core, HChaCha20, or Poly1305
//! fails these ciphertext-and-tag comparisons byte-for-byte.
//!
//! Lengths cross every AEAD boundary: empty/empty, AAD-only, 1 byte, exact
//! Poly1305 block (16), sub/exact/over ChaCha block (63/64/65), multi-block
//! (128+13), chunk-scale (1024+64), and a 4097+129 case that exercises long
//! keystreams and unaligned padding both sides.

use fgdb_crypto::aead::{
    AeadError, chacha20poly1305_open, chacha20poly1305_seal, object_aead_aad,
    xchacha20poly1305_open, xchacha20poly1305_seal,
};

mod vectors {
    // GENERATED by the scratchpad aead_oracle. DO NOT EDIT BY HAND.
    pub const XNONCE: &str = "01080f161d242b323940474e555c636a71787f868d949ba2";
    pub const XCHACHA_VECTORS: &[(usize, usize, &str)] = &[
        (0, 0, "f84cae7da1c91a72143965ff27c3e716"),
        (0, 17, "c560de3ab849c02329131e79bea5c7c4"),
        (1, 0, "ce0476aa5736f4ae2e3236b4b0d8e06f7c"),
        (
            16,
            16,
            "ce2998cbd7aa3bc4c71e2127185c27352d2842d4b3c647bf3de0086af4a35ea1",
        ),
        (
            63,
            5,
            "ce2998cbd7aa3bc4c71e2127185c2735a55cd803eec8ac06d6d1e374607de531e21c868b1dd5a64e885c611ea530a924e69dc45f6a3211df7ca39560b1dfae5f8b06aa09b3414e48e956fd5e58d481",
        ),
        (
            64,
            0,
            "ce2998cbd7aa3bc4c71e2127185c2735a55cd803eec8ac06d6d1e374607de531e21c868b1dd5a64e885c611ea530a924e69dc45f6a3211df7ca39560b1dfae91cedb8fa49c083607ef1f75c22d018880",
        ),
        (
            65,
            32,
            "ce2998cbd7aa3bc4c71e2127185c2735a55cd803eec8ac06d6d1e374607de531e21c868b1dd5a64e885c611ea530a924e69dc45f6a3211df7ca39560b1dfae918a62367319475f6c4e96a130a9c7e1cb10",
        ),
        (
            128,
            13,
            "ce2998cbd7aa3bc4c71e2127185c2735a55cd803eec8ac06d6d1e374607de531e21c868b1dd5a64e885c611ea530a924e69dc45f6a3211df7ca39560b1dfae918a7e262a4d6e30e50219bb32bd8f79094d0fc101e39fe88bb14b834de2b86733128318223dad4944f2bc508d17ba16f81eed3b6df006fe90b3476c118190300813057cf92e6c5bedd5cc4328d473c475",
        ),
    ];
    pub const NONCE12: &str = "0205080b0e1114171a1d2023";
    pub const CHACHA_VECTORS: &[(usize, usize, &str)] = &[
        (0, 0, "9495e7890c1b2c5e40675091920d5509"),
        (
            64,
            12,
            "8a9d2e6d3db09b9d56290cfde284d3bc4caf3b728de71e97cc34c033800a8c04dd8aa2d3a0dc81ee2ee652a2231e1dc74bd3c1bc94021f6e9daa7c15d09e581eefb34bbf10d70c694819aa6ba323b400",
        ),
        (
            129,
            7,
            "8a9d2e6d3db09b9d56290cfde284d3bc4caf3b728de71e97cc34c033800a8c04dd8aa2d3a0dc81ee2ee652a2231e1dc74bd3c1bc94021f6e9daa7c15d09e581e9e905457c6cf4ee5bc0e7bab851feba37501fba7e53125c770363c0dbd07d6f7e89cda872ecfba8b76b1080e52493fec3654c70e466dbe0f4b2ab6651273f8d48ae7723bc23d186c55194e6381e8c615f4",
        ),
    ];
}

fn pattern(len: usize, seed: u8) -> Vec<u8> {
    (0..len)
        .map(|i| ((i + usize::from(seed)) % 251) as u8)
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("fixture hex"))
        .collect()
}

fn key() -> [u8; 32] {
    core::array::from_fn(|i| i as u8)
}

fn xnonce() -> [u8; 24] {
    let bytes = unhex(vectors::XNONCE);
    bytes.as_slice().try_into().expect("24-byte nonce")
}

fn nonce12() -> [u8; 12] {
    let bytes = unhex(vectors::NONCE12);
    bytes.as_slice().try_into().expect("12-byte nonce")
}

#[test]
fn xchacha_seal_matches_oracle() {
    for &(pt_len, aad_len, want) in vectors::XCHACHA_VECTORS {
        let pt = pattern(pt_len, 3);
        let aad = pattern(aad_len, 11);
        let got = xchacha20poly1305_seal(&key(), &xnonce(), &aad, &pt);
        assert_eq!(
            hex(&got),
            want,
            "XChaCha seal diverges at pt_len={pt_len} aad_len={aad_len}"
        );
    }
}

#[test]
fn chacha_seal_matches_oracle() {
    for &(pt_len, aad_len, want) in vectors::CHACHA_VECTORS {
        let pt = pattern(pt_len, 5);
        let aad = pattern(aad_len, 23);
        let got = chacha20poly1305_seal(&key(), &nonce12(), &aad, &pt);
        assert_eq!(
            hex(&got),
            want,
            "ChaCha seal diverges at pt_len={pt_len} aad_len={aad_len}"
        );
        let opened = chacha20poly1305_open(&key(), &nonce12(), &aad, &got)
            .expect("oracle-matching ciphertext must open");
        assert_eq!(opened, pt, "ChaCha open round trip at pt_len={pt_len}");
    }
}

#[test]
fn open_round_trips_and_returns_the_plaintext() {
    for &(pt_len, aad_len, _) in vectors::XCHACHA_VECTORS {
        let pt = pattern(pt_len, 3);
        let aad = pattern(aad_len, 11);
        let sealed = xchacha20poly1305_seal(&key(), &xnonce(), &aad, &pt);
        let opened = xchacha20poly1305_open(&key(), &xnonce(), &aad, &sealed)
            .expect("well-formed ciphertext must open");
        assert_eq!(
            opened, pt,
            "round trip at pt_len={pt_len} aad_len={aad_len}"
        );
    }
}

/// Every single-bit corruption — in the ciphertext body, the tag, the AAD, the
/// key, and the nonce — must fail authentication. AEAD's whole contract.
#[test]
fn any_corruption_fails_closed() {
    let pt = pattern(64, 3);
    let aad = pattern(16, 11);
    let sealed = xchacha20poly1305_seal(&key(), &xnonce(), &aad, &pt);

    for byte_index in 0..sealed.len() {
        let mut corrupted = sealed.clone();
        corrupted[byte_index] ^= 0x01;
        assert_eq!(
            xchacha20poly1305_open(&key(), &xnonce(), &aad, &corrupted),
            Err(AeadError),
            "flipping sealed byte {byte_index} must fail authentication"
        );
    }

    let mut bad_aad = aad.clone();
    bad_aad[0] ^= 0x80;
    assert_eq!(
        xchacha20poly1305_open(&key(), &xnonce(), &bad_aad, &sealed),
        Err(AeadError),
        "AAD corruption must fail authentication"
    );

    let mut bad_key = key();
    bad_key[31] ^= 0x01;
    assert_eq!(
        xchacha20poly1305_open(&bad_key, &xnonce(), &aad, &sealed),
        Err(AeadError),
        "wrong key must fail authentication"
    );

    let mut bad_nonce = xnonce();
    bad_nonce[23] ^= 0x01;
    assert_eq!(
        xchacha20poly1305_open(&key(), &bad_nonce, &aad, &sealed),
        Err(AeadError),
        "wrong nonce must fail authentication"
    );

    assert_eq!(
        xchacha20poly1305_open(&key(), &xnonce(), &aad, &sealed[..15]),
        Err(AeadError),
        "a buffer shorter than one tag must fail closed"
    );
}

/// The §5.1 object-AEAD AAD transcript is a fixed concatenation; prove the
/// order against a manual construction and prove the AAD actually binds.
#[test]
fn object_aead_aad_binds_the_object_identity() {
    let object_id = fgdb_crypto::hash(b"canonical object bytes");
    let descriptor = b"cipher-descriptor-without-digest";
    let aad = object_aead_aad(&object_id, descriptor);

    let mut manual = Vec::new();
    manual.extend_from_slice(b"fgdb:object-aead:v1");
    manual.extend_from_slice(&object_id.0);
    manual.extend_from_slice(descriptor);
    assert_eq!(aad, manual, "AAD transcript order is pinned by §5.1");

    let pt = pattern(128, 3);
    let sealed = xchacha20poly1305_seal(&key(), &xnonce(), &aad, &pt);
    let other_id = fgdb_crypto::hash(b"a different object");
    let other_aad = object_aead_aad(&other_id, descriptor);
    assert_eq!(
        xchacha20poly1305_open(&key(), &xnonce(), &other_aad, &sealed),
        Err(AeadError),
        "a ciphertext must not open under another object's identity"
    );
}
