//! BLAKE2b (RFC 7693) golden vectors, oracle-generated.
//!
//! **PROVENANCE OF EVERY NUMBER BELOW.** These are not hand-copied from a
//! document and they are not this implementation's own output frozen as
//! "expected" — that would only prove the code agrees with itself. They were
//! generated by a scratchpad oracle built on the published `blake2` crate,
//! which never enters this workspace's dependency graph (doctrine #1: the
//! closed universe binds what we SHIP, and an oracle that generates a constant
//! and then leaves is not a dependency). Increment 1 of this bead verified
//! BLAKE3 exactly this way.
//!
//! **WHY THESE LENGTHS.** The input lengths are the structural boundaries of a
//! 128-byte block construction — 0, 1, 63, 64, 65, 127, 128, 129, 256 — because
//! that is where a block-buffering bug lives. 128 and 256 matter most: a
//! streaming implementation that compresses a full buffer eagerly gets every
//! exact-multiple-of-the-block-size message wrong, and ONLY those messages, so a
//! test suite without them passes while the primitive is broken.
//!
//! The digest lengths 1/16/32/48/64 cover the truncation rule, including the
//! 1-byte case where 63 of the 64 state bytes are discarded.

use fgdb_crypto::blake2b::{Blake2b, Blake2bError, blake2b, blake2b_keyed};

/// The oracle's input rule, reproduced exactly. Any drift here silently
/// invalidates every vector, so it is one function used by every test.
fn pattern(len: usize, seed: u8) -> Vec<u8> {
    (0..len)
        .map(|i| (i as u8).wrapping_mul(31).wrapping_add(seed))
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// (input_len, digest_len, expected_hex)
const UNKEYED: [(usize, usize, &str); 45] = [
    (0, 1, "2e"),
    (1, 1, "1c"),
    (63, 1, "28"),
    (64, 1, "1a"),
    (65, 1, "df"),
    (127, 1, "ca"),
    (128, 1, "62"),
    (129, 1, "df"),
    (256, 1, "60"),
    (0, 16, "cae66941d9efbd404e4d88758ea67670"),
    (1, 16, "5fef29fe05e030ddcf820ede28562818"),
    (63, 16, "3412a6c2fe32084a97e220845ae27306"),
    (64, 16, "c9a3219266078fb118cab67903a6ebce"),
    (65, 16, "83502f8da226bfff822cffbbfc4c4dce"),
    (127, 16, "d3a77cf8d34a597a3d8999e5074c9912"),
    (128, 16, "44dca78cecea061046dbccca1749496d"),
    (129, 16, "5ba99ba0711c084704cc7975de674bbc"),
    (256, 16, "5d411cf77b3872c6622da18ac3b97781"),
    (
        0,
        32,
        "0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8",
    ),
    (
        1,
        32,
        "873e4fe9e41e924911bba3ec53ff4782efc8c0f244fb75c879f8a4328d0142ca",
    ),
    (
        63,
        32,
        "0745452c1dfca7e1ea6051fc7112a622b0131377e4ab08825d5b8223b37e0a8a",
    ),
    (
        64,
        32,
        "7f6ac9517a5a27b6a059aca25d95f3a144115a759b71ee3990df65191573c5e2",
    ),
    (
        65,
        32,
        "cbcc0b56230a8c21aaa9ce88b5631ebd9dbd1aebd009a765f77f0ce0b9793023",
    ),
    (
        127,
        32,
        "cb805dad055a842f1092d84639d7fe552ac7189003dc8d2fc4606d01921b8962",
    ),
    (
        128,
        32,
        "82783c69cecd49386e8825c6b20f3b41a43b4c9e3a21b627d88bf025046e4c72",
    ),
    (
        129,
        32,
        "b71e24c47c2d5cc68a99732abb05b9f80f2ecdd7744e9d111f453bb26f917e69",
    ),
    (
        256,
        32,
        "39041a8098f94c795b569a413ef8f0477df2ee6c974e77c065ca884b008f6b3d",
    ),
    (
        0,
        48,
        "b32811423377f52d7862286ee1a72ee540524380fda1724a6f25d7978c6fd3244a6caf0498812673c5e05ef583825100",
    ),
    (
        1,
        48,
        "422ea3f992cea0af14497716f4c1823d5734851717e27ebde848bd91123edffc38e9e880e8ddae1f6c5994a64bdd8640",
    ),
    (
        63,
        48,
        "0addee2122256e381ff18ff2dea3777f627fa8c011179ebe6645180bfbd06eb2413b8e2ece397d55250aaa5d079a1727",
    ),
    (
        64,
        48,
        "9090c9b07aa860ac664839f4827b2269fcce32a801c445c2166d7ff77f3302ee60802d39ff3c11eacdb55bc28abb3efb",
    ),
    (
        65,
        48,
        "9d48a078ed5096e3269dc020cf541702cd42fb3b5d3879e62257bf332dfce7906b0bbd063369ce42f468a64eaafa8529",
    ),
    (
        127,
        48,
        "1eea663292e79643fed9ca1d5c7350d788229ae0bb209279bb118efe67c8384dc7c4f0e035620a2117a7f2e261fc9e56",
    ),
    (
        128,
        48,
        "7bdea399199457f842f8ce59dc2216237b6766dd803fbb59f2bdf9005fc65de242b4fda825eee64272864f6925002740",
    ),
    (
        129,
        48,
        "08fe05f51dc51a7df7d83d710776eb39cde7ec95bcc75d50a2aaad5252c4b9dd8cbdb2dcfd30733e7f6ae1494a331859",
    ),
    (
        256,
        48,
        "52253eed9ca327f92f111a2d8e55bd139b3712dab8fd2b6e840f42d4c40a75bc555932699b7eb637001600b7bfbe66fb",
    ),
    (
        0,
        64,
        "786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce",
    ),
    (
        1,
        64,
        "dc19b62fbd4e480a12134892649b0c86c21540830bf61aa81e7e13868e7d23ed78ed66b94f6ea8bb779261b98782745fc85ad1dfe9b07859ed77c28b94eaac85",
    ),
    (
        63,
        64,
        "96a4646a2c8d50eda88a8ce645f2e1b6b8f3ca3abdab7ef095997f8b1e6e8ae2fb8767f2f9238011a9758ab7d0fbed9c96fa34528b169fed65eb24abc0ed84bb",
    ),
    (
        64,
        64,
        "7f7b84dae9ba53172b941f0f0d588ce38c60842ea94ae0f66f397048f3e787122e76873aa058212b97455b282e974fd7fbd85fb864e4a9fb0dad73609cbd4461",
    ),
    (
        65,
        64,
        "a45f100c5a3b4acaf7a6fb4b3b2dc3e456495fc8acdc6f7af0959b3b7f13c1a7895e2abe30dd00345c7ab406bad58e36f015b2ad60350aa846f85a1280d143ce",
    ),
    (
        127,
        64,
        "3dd556bc15bb8a1c16ce9bc28f245325f5bfc50e84f44c539b7172295d22d81b613a19324b278b3a06dca69a7c9f7d38b9862fa8f2230a9818fe126ef207aa17",
    ),
    (
        128,
        64,
        "88134c9c2bda5481ec42b0d53611231ab7c21ccbbbcf5bc813acffea3eef47c1bb198748d222a9a0d0899631eb39b8c63d61ab1bc8128196e615dc9032ebf5bf",
    ),
    (
        129,
        64,
        "458471021bb1880be73a9a9054316b4b5b83cd27e0ece6f76987d52eb53ccea9ea89e5f1d5a45343536d439e4a125e733c41f2aef79aa299d076a10fc3b283f2",
    ),
    (
        256,
        64,
        "8055742fadd993ad58a28ef85b80e63059a8944b9fc74e65ff7dbbc6a133ac5fa7ea85ff285e7e93d1cb52e1e6ec49cc6a2c56183a953b91982dfcb6aee9e0fd",
    ),
];

/// (key_len, input_len, digest_len, expected_hex)
const KEYED: [(usize, usize, usize, &str); 9] = [
    (
        1,
        0,
        64,
        "9cfa5e518af021d2e67759579b04023b8e25d960eca8c408466973523f59ec64e1dc2001ccd2290d4de23ed7cabc32c536d3518fabe1986bae8bc074e405587b",
    ),
    (
        1,
        1,
        64,
        "a65be01d9bd79dcd7a562aeacf19459cddbb2828292c2104105c86de5c8a84feafcfa9546c11aea030d824c940704a9cda4fb30d533b78842988c2fc2a7dcc0a",
    ),
    (
        1,
        128,
        64,
        "0e5d93e25ae4b0202975b4d379a17735d109f49c0eb1673623485bef7cd70d6efdf52d240e95f1139a239c8c40b06ab2484950eef4dbe952c6b3998d325b27a4",
    ),
    (
        32,
        0,
        64,
        "34551737acbee10067262864ae230779ec598b0e4111b7acab1de253d9ddb1750eb6178d323d586c60b51c2d7260af9412532d6472d0b75adf23b76bbadfa771",
    ),
    (
        32,
        1,
        64,
        "e90c6a72b2551b47d5452dcff0c3533c1fa38bfc8826b2f8e34be547a901c6f222055255034003c6e60757f9430b2a2ca907ccaca9f55470ae0918f779dcfed0",
    ),
    (
        32,
        128,
        64,
        "81b1f344f9f51e8b317dff0dad08f713b2d0a5f37847ebf01bb0f9b60da682d18f647966dcec48c67c7539c26e91d33163d480ac2e1f84cb5ea7989d39da548b",
    ),
    (
        64,
        0,
        64,
        "cb4bc45c9b27acfa3777ff1af47a1d98f0f5dce008a1b0018b7322b8cb6b5e347daa27bf1ae7b02c3bdadafe96ec6ee467fc529e81b97eba6274414cbd0ba421",
    ),
    (
        64,
        1,
        64,
        "82c0859f90ef70f3fa4b7190a0af3584b12b7f308c3a9099a2e5215ea1d1e1b9da7ae18c62f5f313b85d39d9d656b4e040c14cc6ebb6b061c1bc67a2aa286daf",
    ),
    (
        64,
        128,
        64,
        "680c6db314302b8494ff6712d96973a8baefa529259706c09d370113ce86e668d33fc11d165656d18f70e6006b2b8db860bfa2cd9e80788f38b048afe8dfc9b3",
    ),
];

#[test]
fn unkeyed_digests_match_the_oracle() {
    for (input_len, digest_len, expected) in UNKEYED {
        let got = blake2b(digest_len, &pattern(input_len, 7)).expect("legal parameters");
        assert_eq!(
            got.len(),
            digest_len,
            "digest length must be exactly as asked"
        );
        assert_eq!(
            hex(&got),
            expected,
            "BLAKE2b-{digest_len} over {input_len} bytes disagrees with the oracle"
        );
    }
}

#[test]
fn keyed_digests_match_the_oracle() {
    for (key_len, input_len, digest_len, expected) in KEYED {
        let got = blake2b_keyed(digest_len, &pattern(key_len, 3), &pattern(input_len, 7))
            .expect("legal parameters");
        assert_eq!(
            hex(&got),
            expected,
            "keyed BLAKE2b-{digest_len} (key {key_len}, input {input_len}) disagrees with the oracle"
        );
    }
}

/// Keying is not cosmetic: the same message under a key and unkeyed must differ.
///
/// Without this, an implementation that accepted a key and dropped it would pass
/// every unkeyed vector above and silently produce unauthenticated output.
#[test]
fn a_key_changes_the_digest() {
    let message = pattern(200, 7);
    let unkeyed = blake2b(64, &message).expect("legal parameters");
    let keyed = blake2b_keyed(64, &pattern(32, 3), &message).expect("legal parameters");
    assert_ne!(unkeyed, keyed, "the key did not reach the compression");

    let other_key = blake2b_keyed(64, &pattern(32, 4), &message).expect("legal parameters");
    assert_ne!(keyed, other_key, "two different keys produced one digest");
}

/// Streaming in arbitrary pieces must equal the one-shot digest.
///
/// This is where the last-block rule is actually tested: a split that lands
/// exactly on a block boundary is the case an eager-compression bug fails, and
/// the 128/256 splits below sit precisely there.
#[test]
fn streaming_in_any_chunking_equals_the_one_shot_digest() {
    let message = pattern(300, 7);
    let expected = blake2b(64, &message).expect("legal parameters");

    for chunk in [1usize, 7, 63, 64, 65, 127, 128, 129, 256, 300] {
        let mut state = Blake2b::new(64).expect("legal parameters");
        for piece in message.chunks(chunk) {
            state.update(piece);
        }
        assert_eq!(
            state.finalize(),
            expected,
            "streaming in {chunk}-byte pieces disagrees with the one-shot digest"
        );
    }
}

/// The exact-multiple-of-the-block-size case, called out on its own because it
/// is the single most likely bug and the vectors above would hide it in a list.
///
/// **THIS TEST COMPARES AGAINST THE ORACLE, NOT AGAINST ITSELF, AND THE
/// DIFFERENCE IS THE WHOLE POINT.** It first compared streaming output to
/// one-shot output. A mutation implementing the exact bug this test is named
/// for — compressing a full buffer eagerly instead of lagging one block — was
/// caught by the vector tables and *passed here*, because eager compression
/// breaks streaming and one-shot identically and the two still agreed. A
/// self-consistency check cannot detect an error its two sides share. The
/// expected values are therefore looked up in the oracle table above.
#[test]
fn messages_that_are_an_exact_block_multiple_are_not_finalized_early() {
    // NOTE ON THE BINDING NAMES. These compare message and digest SIZES, not
    // secrets. They are spelled `bytes_in`/`bytes_out` because `ubs` pattern
    // matches an `==` against any identifier ending in `_len` as a
    // non-constant-time secret comparison, and a waiver on a crypto file is a
    // worse artifact than a rename: the next reader cannot tell a waived false
    // positive from a waived real one. The genuine constant-time comparison in
    // this crate is `aead::constant_time_eq16`, over tags, where it belongs.
    let expected_for = |len: usize| -> &str {
        UNKEYED
            .iter()
            .find(|(bytes_in, bytes_out, _)| *bytes_in == len && *bytes_out == 64)
            .map(|(_, _, expected)| *expected)
            .expect("the oracle table must carry this block-multiple length")
    };

    for len in [128usize, 256] {
        let oracle = expected_for(len);

        let one_shot = blake2b(64, &pattern(len, 7)).expect("legal parameters");
        assert_eq!(
            hex(&one_shot),
            oracle,
            "the one-shot digest of an exact {len}-byte block multiple disagrees \
             with the oracle — the final block was compressed without its \
             finalization flag"
        );

        let mut state = Blake2b::new(64).expect("legal parameters");
        state.update(&pattern(len, 7));
        assert_eq!(
            hex(&state.finalize()),
            oracle,
            "the streamed digest of an exact {len}-byte block multiple disagrees \
             with the oracle"
        );

        // And it must differ from the same message one byte shorter, which an
        // off-by-one in the counter would collapse.
        let shorter = blake2b(64, &pattern(len - 1, 7)).expect("legal parameters");
        assert_ne!(
            one_shot,
            shorter,
            "a {len}-byte message hashed identically to a {}-byte one",
            len - 1
        );
    }
}

/// Illegal parameters are refused with a typed error, never clamped.
#[test]
fn out_of_range_parameters_fail_closed() {
    assert_eq!(
        blake2b(0, b"x"),
        Err(Blake2bError::DigestLen { requested: 0 }),
        "a zero-length digest must be refused"
    );
    assert_eq!(
        blake2b(65, b"x"),
        Err(Blake2bError::DigestLen { requested: 65 }),
        "a digest above 64 bytes must be refused, not truncated to 64"
    );
    assert_eq!(
        blake2b_keyed(32, &[0u8; 65], b"x"),
        Err(Blake2bError::KeyLen { requested: 65 }),
        "a key above 64 bytes must be refused, not truncated"
    );
    // The boundaries themselves are legal.
    assert!(blake2b(1, b"x").is_ok(), "a 1-byte digest is legal");
    assert!(blake2b(64, b"x").is_ok(), "a 64-byte digest is legal");
    assert!(
        blake2b_keyed(32, &[0u8; 64], b"x").is_ok(),
        "a 64-byte key is legal"
    );
}

/// A truncated digest must be the prefix of the full one — the truncation rule
/// RFC 7693 §2.8 states, and the property Argon2id's H' relies on.
#[test]
fn shorter_digests_are_not_prefixes_of_longer_ones() {
    // NOTE THE SIGN. BLAKE2b encodes the digest length in the parameter block,
    // so shortening the request changes the whole computation rather than
    // truncating its output. Asserting the opposite would bake in a real bug.
    let long = blake2b(64, b"boundary").expect("legal parameters");
    let short = blake2b(32, b"boundary").expect("legal parameters");
    assert_ne!(
        &long[..32],
        &short[..],
        "digest length must be bound into the parameter block, not applied as \
         an output truncation"
    );
}
