//! Oracle-verified BLAKE3 vectors for the in-house implementation.
//!
//! PROVENANCE. The fixture module below was GENERATED on 2026-07-28 by a
//! dev-time oracle program (scratchpad `b3oracle`, outside this workspace)
//! linking the official `blake3` crate v1. Inputs follow the official BLAKE3
//! test-vector convention: for length N, the input is the repeating byte
//! pattern 0,1,...,250,0,1,...; the key and derive-key context are the
//! official test-vector strings. The oracle is not a dependency of anything
//! here — these are frozen goldens, and the doctrine's closed dependency
//! universe stays closed.
//!
//! The length set deliberately covers every structural boundary: empty input,
//! sub-block, exact block (64), block+1, multi-block, exact chunk (1024),
//! chunk+1, every tree shape through 8 chunks (8192) plus deeper trees
//! (16384 = 16 chunks, 31744 = 31 chunks, 102400 = 100 chunks) so the lazy
//! chaining-value-stack merge logic is exercised at odd and even chunk counts.

use fgdb_crypto::blake3::{Hasher, derive_key, hash, keyed_hash};

mod vectors {
    // GENERATED by the scratchpad b3oracle against the official blake3 crate.
    // DO NOT EDIT BY HAND.
    pub const KEY: &[u8; 32] = b"whats the Elephant doing tonight";
    pub const CONTEXT: &str = "BLAKE3 2019-12-27 16:29:52 test vectors context";

    /// (input_len, hash_hex, keyed_hash_hex, derive_key_hex)
    pub const VECTORS: &[(usize, &str, &str, &str)] = &[
        (
            0,
            "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
            "200218fd1a80c38d356e72e1dceae57650c1de03c88157bd1891235fe08e99c0",
            "2cc39783c223154fea8dfb7c1b1660f2ac2dcbd1c1de8277b0b0dd39b7e50d7d",
        ),
        (
            1,
            "2d3adedff11b61f14c886e35afa036736dcd87a74d27b5c1510225d0f592e213",
            "5a03b1a36c2368672a9ab719ac39e10becf868c3b473e953e01c13872ff93d89",
            "b3e2e340a117a499c6cf2398a19ee0d29cca2bb7404c73063382693bf66cb06c",
        ),
        (
            2,
            "7b7015bb92cf0b318037702a6cdd81dee41224f734684c2c122cd6359cb1ee63",
            "fef2f1856c85f80c0e1a8c938313b4b08434ca124a2b602bd136461a801cc19e",
            "1f166565a7df0098ee65922d7fea425fb18b9943f19d6161e2d17939356168e6",
        ),
        (
            3,
            "e1be4d7a8ab5560aa4199eea339849ba8e293d55ca0a81006726d184519e647f",
            "9e4d1b866b1ad271baa1e2164e678a33f926df92a685ee6399c18c6f3fbb102e",
            "440aba35cb006b61fc17c0529255de438efc06a8c9ebf3f2ddac3b5a86705797",
        ),
        (
            4,
            "f30f5ab28fe047904037f77b6da4fea1e27241c5d132638d8bedce9d40494f32",
            "23a0e2521f6e8cb212ffee8c0f5c98bb64606fd5fce3bd999c985d12c5f129ec",
            "f46085c8190d69022369ce1a18880e9b369c135eb93f3c63550d3e7630e91060",
        ),
        (
            63,
            "e9bc37a594daad83be9470df7f7b3798297c3d834ce80ba85d6e207627b7db7b",
            "406a60e86232b4871830c750f38ce2b6493d219c9bf80ea2296d6c5a3ea266bc",
            "b6451e30b953c206e34644c6803724e9d2725e0893039cfc49584f991f451af3",
        ),
        (
            64,
            "4eed7141ea4a5cd4b788606bd23f46e212af9cacebacdc7d1f4c6dc7f2511b98",
            "92563409532e8269b525b2488efd8c48c1a0fa42671a442e7da0f5d644bbcee5",
            "a5c4a7053fa86b64746d4bb688d06ad1f02a18fce9afd3e818fefaa7126bf73e",
        ),
        (
            65,
            "de1e5fa0be70df6d2be8fffd0e99ceaa8eb6e8c93a63f2d8d1c30ecb6b263dee",
            "64269d72fb480b5fe67fc88dc48b225f922c6c78d5a335a1745c789c59e713ed",
            "51fd05c3c1cfbc8ed67d139ad76f5cf8236cd2acd26627a30c104dfd9d3ff8a8",
        ),
        (
            127,
            "d81293fda863f008c09e92fc382a81f5a0b4a1251cba1634016a0f86a6bd640d",
            "d9f55c58db84041dc3ed3a59cc33b288b6c9adac2c4e4a493de965abb4a96e62",
            "c91c090ceee3a3ac81902da31838012625bbcd73fcb92e7d7e56f78deba4f0c3",
        ),
        (
            128,
            "f17e570564b26578c33bb7f44643f539624b05df1a76c81f30acd548c44b45ef",
            "b44a05f40247bf1c005538fff95ef13497885527848ca9aec842c24ab8771f0a",
            "81720f34452f58a0120a58b6b4608384b5c51d11f39ce97161a0c0e442ca0225",
        ),
        (
            129,
            "683aaae9f3c5ba37eaaf072aed0f9e30bac0865137bae68b1fde4ca2aebdcb12",
            "8f8458438c9e8d4a2d3ee7b836fa5335ff6fc6279b16c7ce7d6c82dcdebec68d",
            "938d2d4435be30eafdbb2b7031f7857c98b04881227391dc40db3c7b21f41fc1",
        ),
        (
            1023,
            "10108970eeda3eb932baac1428c7a2163b0e924c9a9e25b35bba72b28f70bd11",
            "4e85470c877f9cbbe9353b2fc3a9442db4b88e085120b20a9449b84270fb26c2",
            "74a16c1c3d44368a86e1ca6df64be6a2f64cce8f09220787450722d85725dea5",
        ),
        (
            1024,
            "42214739f095a406f3fc83deb889744ac00df831c10daa55189b5d121c855af7",
            "a635e7aa8cd2faf3594c51212916231caa1078f49e0b5e0967bae896811f01ca",
            "7356cd7720d5b66b6d0697eb3177d9f8d73a4a5c5e968896eb6a689684302706",
        ),
        (
            1025,
            "d00278ae47eb27b34faecf67b4fe263f82d5412916c1ffd97c8cb7fb814b8444",
            "7977d206ba67db4c37971b9a7ef8b03ca4a4d3387bd0e64af45096255c3acf6b",
            "effaa245f065fbf82ac186839a249707c3bddf6d3fdda22d1b95a3c970379bcb",
        ),
        (
            2048,
            "e776b6028c7cd22a4d0ba182a8bf62205d2ef576467e838ed6f2529b85fba24a",
            "fafb69250d89696b3a0b722928dcc5d590866120dc0c747adad28a1e11201860",
            "7b2945cb4fef70885cc5d78a87bf6f6207dd901ff239201351ffac04e1088a23",
        ),
        (
            2049,
            "5f4d72f40d7a5f82b15ca2b2e44b1de3c2ef86c426c95c1af0b6879522563030",
            "83ab486022445421dad28c356af94c9d911112ef782637b925bbc7c17a78d986",
            "2ea477c5515cc3dd606512ee72bb3e0e758cfae7232826f35fb98ca1bcbdf273",
        ),
        (
            3072,
            "b98cb0ff3623be03326b373de6b9095218513e64f1ee2edd2525c7ad1e5cffd2",
            "225808999423f5f43f516618f9c042d8e9ffc5b8a8168d76718fd50af7afc2ab",
            "050df97f8c2ead654d9bb3ab8c9178edcd902a32f8495949feadcc1e0480c46b",
        ),
        (
            3073,
            "7124b49501012f81cc7f11ca069ec9226cecb8a2c850cfe644e327d22d3e1cd3",
            "347677781c7ea46b2dd64da00aab31d821dac437a217a3567863521e522df336",
            "72613c9ec9ff7e40f8f5c173784c532ad852e827dba2bf85b2ab4b76f7079081",
        ),
        (
            4096,
            "015094013f57a5277b59d8475c0501042c0b642e531b0a1c8f58d2163229e969",
            "c1e6db8160d110541256594012c4e9c91011dde71063ed0fdd4428085dd730a7",
            "1e0d7f3db8c414c97c6307cbda6cd27ac3b030949da8e23be1a1a924ad2f25b9",
        ),
        (
            4097,
            "9b4052b38f1c5fc8b1f9ff7ac7b27cd242487b3d890d15c96a1c25b8aa0fb995",
            "743568c8352c8a2e2460f768fc14dd9cf162b9e2959581a010cff917465581b9",
            "aca51029626b55fda7117b42a7c211f8c6e9ba4fe5b7a8ca922f34299500ead8",
        ),
        (
            5120,
            "9cadc15fed8b5d854562b26a9536d9707cadeda9b143978f319ab34230535833",
            "ded1eee7ccdfd40e89bd53b388b59a4dda374fe9f0fd5bcfb011a7f8178b5afd",
            "7a7acac8a02adcf3038d74cdd1d34527de8a0fcc0ee3399d1262397ce5817f60",
        ),
        (
            5121,
            "628bd2cb2004694adaab7bbd778a25df25c47b9d4155a55f8fbd79f2fe154cff",
            "4a1872e28f67e9ba2f1bb821451f1562991f9e6ec54f884805b9e3694dadd0a8",
            "b07f01e518e702f7ccb44a267e9e112d403a7b3f4883a47ffbed4b48339b3c34",
        ),
        (
            6144,
            "3e2e5b74e048f3add6d21faab3f83aa44d3b2278afb83b80b3c35164ebeca205",
            "63402fd9c639f038c4ac1da5670d6dd86ffdb2f0467460ac35b716cbfdce5002",
            "2a95beae63ddce523762355cf4b9c1d8f131465780a391286a5d01abb5683a15",
        ),
        (
            6145,
            "f1323a8631446cc50536a9f705ee5cb619424d46887f3c376c695b70e0f0507f",
            "e27b3c5dd6ec065d0c256d2df3bdf8ae0e3b8c1ccc9e033eaec295366eee2730",
            "379bcc61d0051dd489f686c13de00d5b14c505245103dc040d9e4dd1facab8e5",
        ),
        (
            7168,
            "61da957ec2499a95d6b8023e2b0e604ec7f6b50e80a9678b89d2628e99ada77a",
            "4f212abca41b1f219a53fb93318e2be183f36b9618d46e80a99828d2f15fba9c",
            "11c37a112765370c94a51415d0d651190c288566e295d505defdad895dae2237",
        ),
        (
            7169,
            "a003fc7a51754a9b3c7fae0367ab3d782dccf28855a03d435f8cfe74605e7817",
            "cc190e3b5160994373b5bd95ceae687944ae5c83914a58115a929ae466023544",
            "554b0a5efea9ef183f2f9b931b7497995d9eb26f5c5c6dad2b97d62fc5ac31d9",
        ),
        (
            8192,
            "aae792484c8efe4f19e2ca7d371d8c467ffb10748d8a5a1ae579948f718a2a63",
            "8d10792472f321076543172af8b04e64510dac30af31a6b022e020cd7b636aa3",
            "ad01d7ae4ad059b0d33baa3c01319dcf8088094d0359e5fd45d6aeaa8b2d0c3d",
        ),
        (
            8193,
            "bab6c09cb8ce8cf459261398d2e7aef35700bf488116ceb94a36d0f5f1b7bc3b",
            "a1640729a7fa2567f7ba47619202b8bc678621be56c547328389d5bccf259df9",
            "af1e0346e389b17c23200270a64aa4e1ead98c61695d917de7d5b00491c9b0f1",
        ),
        (
            16384,
            "f875d6646de28985646f34ee13be9a576fd515f76b5b0a26bb324735041ddde4",
            "fb29467bdf0e18e0be3becc1237c62dc16b541b6d81f8d083b93dd5dd6673b3f",
            "160e18b5878cd0df1c3af85eb25a0db5344d43a6fbd7a8ef4ed98d0714c3f7e1",
        ),
        (
            31744,
            "62b6960e1a44bcc1eb1a611a8d6235b6b4b78f32e7abc4fb4c6cdcce94895c47",
            "cd82f8104887987d8704d536060d7518929f80e0e13d2ae0b927a3c424f0252d",
            "39772aef80e0ebe60596361e45b061e8f417429d529171b6764468c22928e28e",
        ),
        (
            102400,
            "bc3e3d41a1146b069abffad3c0d44860cf664390afce4d9661f7902e7943e085",
            "eaf688a13ca2d538a568481b47ecae614e2bc5453cf1d522734ba4e96394c12f",
            "4652cff7a3f385a6103b5c260fc1593e13c778dbe608efb092fe7ee69df6e9c6",
        ),
    ];

    pub const XOF_0: &str = "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262e00f03e7b69af26b7faaf09fcd333050338ddfe085b8cc869ca98b206c08243a26f5487789e8f660afe6c99ef9e0c52b92e7393024a80459cf91f476f9ffdbda7001c22e159b402631f277ca96f2defdf1078282314e763699a31c5363165421cce14d";
    pub const XOF_1024: &str = "42214739f095a406f3fc83deb889744ac00df831c10daa55189b5d121c855af71cf8107265ecdaf8505b95d8fcec83a98a6a96ea5109d2c179c47a387ffbb404756f6eeae7883b446b70ebb144527c2075ab8ab204c0086bb22b7c93d465efc57f8d917f0b385c6df265e77003b85102967486ed57db5c5ca170ba441427ed9afa684e";
}

fn pattern(len: usize) -> Vec<u8> {
    (0..len).map(|i| (i % 251) as u8).collect()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn one_shot_matches_oracle_for_every_structural_boundary() {
    for &(len, want_hash, want_keyed, want_derived) in vectors::VECTORS {
        let input = pattern(len);
        assert_eq!(
            hash(&input).to_hex(),
            want_hash,
            "plain hash diverges from the oracle at input_len={len}"
        );
        assert_eq!(
            keyed_hash(vectors::KEY, &input).to_hex(),
            want_keyed,
            "keyed hash diverges from the oracle at input_len={len}"
        );
        assert_eq!(
            hex(&derive_key(vectors::CONTEXT, &input)),
            want_derived,
            "derive_key diverges from the oracle at input_len={len}"
        );
    }
}

/// Streaming must be split-invariant: any partition of the input into update
/// calls yields the same digest as the one-shot path. The splits cross block
/// and chunk boundaries on purpose.
#[test]
fn streaming_is_split_invariant() {
    for &(len, want_hash, _, _) in vectors::VECTORS {
        let input = pattern(len);
        for &split in &[1usize, 63, 64, 65, 1023, 1024, 1025] {
            if split >= len && split != 1 {
                continue;
            }
            let mut hasher = Hasher::new();
            for piece in input.chunks(split) {
                hasher.update(piece);
            }
            assert_eq!(
                hasher.finalize().to_hex(),
                want_hash,
                "split={split} diverges at input_len={len}"
            );
        }
    }
}

/// XOF output must be prefix-consistent with finalize() and match the oracle
/// beyond 32 bytes (131 bytes crosses two 64-byte output blocks plus a tail).
#[test]
fn xof_matches_oracle_and_is_prefix_consistent() {
    for (len, want) in [(0usize, vectors::XOF_0), (1024usize, vectors::XOF_1024)] {
        let input = pattern(len);
        let mut out = [0u8; 131];
        let mut hasher = Hasher::new();
        hasher.update(&input);
        hasher.finalize_xof(&mut out);
        assert_eq!(hex(&out), want, "XOF diverges at input_len={len}");
        assert_eq!(
            out[..32],
            hasher.finalize().0,
            "finalize() must be the 32-byte XOF prefix at input_len={len}"
        );
    }
}

/// The identity-transcript helpers are pure concatenation under the pinned
/// domain strings — prove the transcript order against a manual construction.
#[test]
fn identity_transcripts_match_manual_concatenation() {
    let k_oid = vectors::KEY;
    let namespace = [0x5au8; 32];
    let header = b"hdr";
    let payload = b"payload-bytes";

    let via_helper = fgdb_crypto::logical_object_id(k_oid, &namespace, header, payload);

    let mut manual = Vec::new();
    manual.extend_from_slice(b"fgdb:logical:v1");
    manual.extend_from_slice(&namespace);
    manual.extend_from_slice(header);
    manual.extend_from_slice(payload);
    assert_eq!(via_helper, keyed_hash(k_oid, &manual));

    let descriptor = b"canonical-descriptor";
    let mut enc_manual = Vec::new();
    enc_manual.extend_from_slice(b"fgdb:encoding:v1");
    enc_manual.extend_from_slice(descriptor);
    assert_eq!(fgdb_crypto::encoding_id(descriptor), hash(&enc_manual));

    let mut plc_manual = Vec::new();
    plc_manual.extend_from_slice(b"fgdb:placement:v1");
    plc_manual.extend_from_slice(descriptor);
    assert_eq!(fgdb_crypto::placement_id(descriptor), hash(&plc_manual));
}

/// Domain separation: the three identity functions and the two keyed modes
/// must never collide on identical input bytes.
#[test]
fn modes_and_domains_are_separated() {
    let input = pattern(64);
    let plain = hash(&input);
    let keyed = keyed_hash(vectors::KEY, &input);
    let derived = derive_key(vectors::CONTEXT, &input);
    assert_ne!(plain.0, keyed.0);
    assert_ne!(plain.0, derived);
    assert_ne!(keyed.0, derived);

    let descriptor = b"same-bytes";
    assert_ne!(
        fgdb_crypto::encoding_id(descriptor),
        fgdb_crypto::placement_id(descriptor),
        "encoding and placement domains must separate identical descriptors"
    );
}
