#!/usr/bin/env bash
# =============================================================================
# g0_threat_e2e.sh — end-to-end threat/trust-model gate (fgdb-g0-threat-model-nqd)
# =============================================================================
# Builds the threat-model document and footprint tables from their registry
# sources, runs the generated completeness check over every registered posture
# and all eleven external authorities, executes the attenuation property suite,
# and scans the merged normative text for claims exceeding the trust matrix,
# failing with file and line.
#
# The temporary evidence directory is intentionally retained: repository policy
# forbids automated deletion, and the NDJSON streams are useful replay artifacts.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

EVIDENCE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/fgdb-threat-e2e.XXXXXX")"
FIRST="$EVIDENCE_DIR/first.ndjson"
SECOND="$EVIDENCE_DIR/second.ndjson"
TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/target}"
case "$TARGET_DIR" in
  /*) ;;
  *) TARGET_DIR="$ROOT/$TARGET_DIR" ;;
esac
BIN="$TARGET_DIR/debug/threat-check"
REGISTRY="$ROOT/registries/threat_model.toml"
DOCUMENT="$ROOT/docs/THREAT_AND_TRUST_MODEL.md"

echo "==> build threat-check"
cargo build -p registry-check --bin threat-check
test -x "$BIN"

echo "==> validate the frozen threat model twice (determinism)"
"$BIN" --root "$ROOT" >"$FIRST"
"$BIN" --root "$ROOT" >"$SECOND"
cmp "$FIRST" "$SECOND"

echo "==> prove the published document is generated, not hand-authored"
# Regenerating into a scratch tree must reproduce the committed bytes exactly.
DOC_BEFORE="$(sha256sum "$DOCUMENT" | cut -d' ' -f1)"
"$BIN" --root "$ROOT" --write >/dev/null
DOC_AFTER="$(sha256sum "$DOCUMENT" | cut -d' ' -f1)"
if [[ "$DOC_BEFORE" != "$DOC_AFTER" ]]; then
  echo "ERROR: docs/THREAT_AND_TRUST_MODEL.md is not the regenerated bytes" >&2
  echo "  before=$DOC_BEFORE after=$DOC_AFTER" >&2
  exit 1
fi
rg -q '"event":"threat_registry_checked".*"document_matches":true' "$FIRST"

# Expectations that MOVE when the registry moves are derived from the registry,
# not hand-copied. The registry is an artifact independent of the binary under
# test, so this still cross-checks two sources rather than comparing output to
# itself. Values fixed by the PLAN (8 actors, 16 classes, 11 authorities) stay
# literal on purpose: those are the enumerations the gate exists to freeze.
registry_scalar() {
  awk -v key="$1" '
    /^\[registry\]/ { inblock = 1; next }
    /^\[/ { inblock = 0 }
    inblock && $1 == key { gsub(/"/, "", $3); print $3; found = 1; exit }
    END { if (!found) { print "registry key " key " not found" > "/dev/stderr"; exit 42 } }
  ' "$REGISTRY"
}
EXPECT_POSTURES="$(registry_scalar posture_count)"
EXPECT_EXPOSURES="$(registry_scalar exposure_cell_count)"
EXPECT_ID_HASH="$(registry_scalar id_table_hash)"
EXPECT_SEMANTIC_HASH="$(registry_scalar semantic_contract_hash)"
EXPECT_AUTHORITY_CELLS=$((EXPECT_POSTURES * 11))

echo "==> assert the completeness matrices are fully logged"
test "$(rg -c '"event":"exposure_cell_checked"' "$FIRST")" -eq "$EXPECT_EXPOSURES"
test "$(rg -c '"event":"authority_row_checked"' "$FIRST")" -eq "$EXPECT_AUTHORITY_CELLS"
test "$(rg -c '"event":"posture_cell_checked"' "$FIRST")" -eq 12
test "$(rg -c '"event":"posture_checked"' "$FIRST")" -eq "$EXPECT_POSTURES"
test "$(rg -c '"event":"attenuation_case"' "$FIRST")" -eq 11
test "$(rg -c '"event":"binding_transition_checked"' "$FIRST")" -eq 9
test "$(rg -c '"event":"source_block_checked"' "$FIRST")" -eq 4
rg -q '"event":"threat_registry_checked".*"id_table_hash":"'"$EXPECT_ID_HASH"'".*"semantic_contract_hash":"'"$EXPECT_SEMANTIC_HASH"'".*"violations":0.*"outcome":"pass"' "$FIRST"
rg -q '"event":"claim_scan_completed".*"flags":0.*"evidence_class":"lint".*"outcome":"pass"' "$FIRST"
if rg -q '"event":"threat_violation"' "$FIRST"; then
  echo "ERROR: unexpected threat violation event" >&2
  exit 1
fi
if rg -q '"event":"claim_scan_flag"' "$FIRST"; then
  echo "ERROR: a normative sentence exceeds the declared trust matrix" >&2
  rg '"event":"claim_scan_flag"' "$FIRST" >&2
  exit 1
fi

echo "==> assert the embedded-DirectoryBound footprint is explicitly empty"
test "$(rg -c '"event":"authority_row_checked".*"posture":"local_directory_bound".*"cell_status":"empty_declared"' "$FIRST")" -eq 11
test "$(rg -c '"event":"authority_row_checked".*"posture":"local_external_cas".*"cell_status":"present"' "$FIRST")" -eq 11
rg -q '"event":"authority_row_checked".*"posture":"local_external_cas".*"authority":"audit_continuity".*"on_synchronous_path":true.*"touch_count":3' "$FIRST"
rg -q '"event":"authority_row_checked".*"posture":"local_external_cas".*"authority":"time_authority".*"touch_count":2' "$FIRST"

echo "==> structurally parse every baseline NDJSON row"
python3 - "$FIRST" "$REGISTRY" <<'PY'
import collections
import json
import sys


def reject_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key {key!r}")
        result[key] = value
    return result


def registry_scalars(path):
    """Read the declared [registry] block; independent of the binary."""
    scalars, inblock = {}, False
    with open(path, encoding="utf-8") as stream:
        for raw in stream:
            line = raw.strip()
            if line == "[registry]":
                inblock = True
                continue
            if line.startswith("["):
                inblock = False
                continue
            if inblock and " = " in line:
                key, _, value = line.partition(" = ")
                scalars[key.strip()] = value.strip().strip('"')
    for required in ("posture_count", "exposure_cell_count", "id_table_hash"):
        assert required in scalars, f"[registry] is missing {required}"
    return scalars


DECLARED = registry_scalars(sys.argv[2])

events = []
with open(sys.argv[1], encoding="utf-8") as stream:
    for line_number, line in enumerate(stream, 1):
        value = json.loads(line, object_pairs_hook=reject_duplicate_keys)
        assert isinstance(value, dict), (line_number, value)
        assert isinstance(value.get("event"), str), (line_number, value)
        events.append(value)

counts = collections.Counter(event["event"] for event in events)
assert counts["threat_registry_checked"] == 1, counts
assert counts["threat_violation"] == 0, counts
assert counts["claim_scan_flag"] == 0, counts
assert counts["claim_scan_completed"] == 1, counts
assert counts["exposure_cell_checked"] == int(DECLARED["exposure_cell_count"]), counts
assert counts["posture_cell_checked"] == 12, counts

registry = next(e for e in events if e["event"] == "threat_registry_checked")
assert registry["violations"] == 0 and registry["outcome"] == "pass", registry
assert registry["actor_count"] == 8, registry
assert registry["operation_class_count"] == 16, registry
assert registry["external_authority_count"] == 11, registry
assert registry["authority_dimension_count"] == 27, registry
assert registry["id_table_hash"] == DECLARED["id_table_hash"], registry
assert registry["document_matches"] is True, registry

# Exposure completeness, recomputed from the stream rather than trusted.
exposures = [e for e in events if e["event"] == "exposure_cell_checked"]
actors = {e["actor"] for e in exposures}
assets = {e["asset"] for e in exposures}
assert len(actors) == 8, sorted(actors)
assert len(assets) == 8, sorted(assets)
seen = collections.Counter((e["actor"], e["asset"]) for e in exposures)
for actor in actors:
    for asset in assets:
        assert seen[(actor, asset)] == 1, (actor, asset, seen[(actor, asset)])
for exposure in exposures:
    assert exposure["disposition"] in {"defended", "conditional", "undefended"}, exposure
    assert exposure["assumption"].startswith("A-"), exposure

# The compromised-server row is the one a reader will check first.
compromised = {
    e["asset"]: e["disposition"]
    for e in exposures
    if e["actor"] == "compromised_operator_or_server"
}
assert compromised["plaintext_graph_data"] == "undefended", compromised
assert compromised["key_material"] == "undefended", compromised
assert "defended" not in compromised.values(), compromised

# Product-space closure: every cell resolved, none unresolved.
cells = [e for e in events if e["event"] == "posture_cell_checked"]
resolutions = collections.Counter(cell["resolution"] for cell in cells)
assert resolutions["unresolved"] == 0, resolutions
assert resolutions["registered"] == int(DECLARED["posture_count"]), resolutions
assert resolutions["excluded"] > 0 and resolutions["deferred"] > 0, resolutions
for cell in cells:
    assert cell["resolved_by"], cell

# Footprint completeness: every (posture, authority) cell present or empty-declared.
rows = [e for e in events if e["event"] == "authority_row_checked"]
assert all(row["cell_status"] in {"present", "empty_declared"} for row in rows), rows
by_posture = collections.Counter(row["posture"] for row in rows)
assert set(by_posture.values()) == {11}, by_posture

# The attenuation law must be two-sided and every case must name a fixture.
laws = [e for e in events if e["event"] == "attenuation_case"]
classes = collections.Counter(law["class"] for law in laws)
assert classes["permitted"] > 0 and classes["prohibited"] > 0, classes
for law in laws:
    assert law["negative_fixture"].startswith("tm_neg_"), law
    assert law["dimensions"], law

# Presentation-binding narrowing: exactly three illegal cells, all weakenings.
transitions = [e for e in events if e["event"] == "binding_transition_checked"]
assert len(transitions) == 9, transitions
illegal = [t for t in transitions if not t["legal"]]
assert len(illegal) == 3, illegal
assert all(t["law"] == "weakened_binding" for t in illegal), illegal
PY

echo "==> generate typed negative registry fixtures"
python3 - "$REGISTRY" "$EVIDENCE_DIR" <<'PY'
from pathlib import Path
import sys

source = Path(sys.argv[1]).read_text(encoding="utf-8")
out = Path(sys.argv[2])


def mutate(name, original, replacement):
    assert source.count(original) == 1, (name, original)
    (out / name).write_text(source.replace(original, replacement, 1), encoding="utf-8")


# An exposure cell silently dropped — the failure the completeness law exists for.
mutate(
    "exposure-dropped.toml",
    '  "key_material:A-NO-TEE",\n',
    "",
)
# A widening presentation-binding transition declared legal.
mutate(
    "binding-weakened.toml",
    '[[binding_transition]]\nfrom = "ChannelBound"\nto = "SessionBound"\nlegal = false\nlaw = "weakened_binding"',
    '[[binding_transition]]\nfrom = "ChannelBound"\nto = "SessionBound"\nlegal = true\nlaw = "further_restrict"',
)
# An authority-domain dimension made intersectable — a chain could narrow its
# way into a different tenant.
mutate(
    "domain-intersectable.toml",
    'id = "tenant"\nsource_order = 1\nnarrowing_operator = "fixed"',
    'id = "tenant"\nsource_order = 1\nnarrowing_operator = "intersect"',
)
# A footprint cell inventing an operation class §16.8 never named.
mutate(
    "invented-operation-class.toml",
    'authority_id = "kms_hsm"\non_synchronous_path = true\ntouch_count = 1\nsync_path_position = "Only at a key-unwrap miss."\noperation_class_basis = "trigger_site_only"\noperation_classes = []',
    'authority_id = "kms_hsm"\non_synchronous_path = true\ntouch_count = 1\nsync_path_position = "Only at a key-unwrap miss."\noperation_class_basis = "trigger_site_only"\noperation_classes = ["KeyManage"]',
)
PY

run_failure() {
  local fixture="$1"
  local expected_code="$2"
  local output="$EVIDENCE_DIR/${fixture%.toml}.ndjson"
  local status=0
  "$BIN" --root "$ROOT" --registry "$EVIDENCE_DIR/$fixture" >"$output" 2>"$output.stderr" || status=$?
  if [[ $status -ne 1 ]]; then
    echo "ERROR: expected exit 1 for $fixture, got $status" >&2
    exit 1
  fi
  if ! rg -q '"event":"threat_violation".*"code":"'"$expected_code"'"' "$output"; then
    echo "ERROR: $fixture did not report $expected_code" >&2
    rg -o '"code":"[^"]*"' "$output" >&2 || true
    exit 1
  fi
}

echo "==> prove the CLI fails closed on each typed defect"
run_failure exposure-dropped.toml exposure_missing
run_failure binding-weakened.toml binding_transition_legality
run_failure domain-intersectable.toml semantic_contract_hash
run_failure invented-operation-class.toml footprint_unsourced_operation_class

echo "==> prove the claim scan goes red on a real overreach"
# The scan's green means nothing unless it has been seen to fail. Inject a
# sentence that claims confidentiality against a compromised server into the
# text the scanner reads, via a registry summary that reaches the document.
OVERREACH="$EVIDENCE_DIR/overreach.toml"
python3 - "$REGISTRY" "$OVERREACH" <<'PY'
from pathlib import Path
import sys

source = Path(sys.argv[1]).read_text(encoding="utf-8")
anchor = 'summary = "Any principal presenting a token over a protocol surface.'
assert source.count(anchor) == 1
injected = (
    'summary = "Graph data stays confidential against a compromised server. '
    "Any principal presenting a token over a protocol surface."
)
Path(sys.argv[2]).write_text(source.replace(anchor, injected, 1), encoding="utf-8")
PY
OVERREACH_OUT="$EVIDENCE_DIR/overreach.ndjson"
OVERREACH_STATUS=0
"$BIN" --root "$ROOT" --registry "$OVERREACH" >"$OVERREACH_OUT" 2>"$OVERREACH_OUT.stderr" || OVERREACH_STATUS=$?
if [[ $OVERREACH_STATUS -ne 1 ]]; then
  echo "ERROR: the claim scan did not fail on an overreaching sentence (exit $OVERREACH_STATUS)" >&2
  exit 1
fi
rg -q '"event":"claim_scan_flag".*"rule_id":"TMS-1"' "$OVERREACH_OUT"
# The failure must carry file and line, per the bead's logging contract.
rg -q '"event":"claim_scan_flag".*"line":[0-9]+' "$OVERREACH_OUT"
rg -q 'claim-scan\[TMS-1\] docs/THREAT_AND_TRUST_MODEL\.md:[0-9]+:' "$OVERREACH_OUT.stderr"

echo "==> run the attenuation property and typed mutation suite"
cargo test -p registry-check --test threat_model

echo "THREAT MODEL E2E GREEN; retained deterministic evidence: $EVIDENCE_DIR"
