#!/usr/bin/env bash
# =============================================================================
# g0_topology_e2e.sh — end-to-end workspace-topology gate
#                      (fgdb-g0-workspace-topology-1q9m)
# =============================================================================
# Builds topology-check, validates the frozen map twice for determinism, proves
# the published document is generated rather than hand-authored, asserts the
# structured event stream is complete against the registry's own declared
# cardinalities, and then seeds six deliberate violations into a scratch copy —
# each of which must fail with its exact violation code.
#
# The seeded fixtures are the point. A checker that has only ever been green is
# a checker nobody has watched work, and this appendix has already produced
# several defects whose signature was "looks exactly like a pass".
#
# The temporary evidence directory is intentionally retained: repository policy
# forbids automated deletion, and the NDJSON streams are useful replay artifacts.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# The shared verdict contract (fgdb-udco). Fail-fast under `set -e` with no
# assertion-level emitter: the EXIT trap derives the `FAIL` line on stdout from
# the exit code. This gate already ended with `echo "PASS: g0_topology_e2e"` —
# anchored, but `PASS:` rather than `PASS `, which is exactly the near-miss the
# contract's closed vocabulary exists to stop drifting into a fifth token.
# shellcheck source=lib/gate_verdict.sh
. "$ROOT/scripts/lib/gate_verdict.sh"
gate_init "g0_topology_e2e"

EVIDENCE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/fgdb-topology-e2e.XXXXXX")"
FIRST="$EVIDENCE_DIR/first.ndjson"
SECOND="$EVIDENCE_DIR/second.ndjson"
TARGET_DIR="${CARGO_TARGET_DIR:-$ROOT/target}"
case "$TARGET_DIR" in
  /*) ;;
  *) TARGET_DIR="$ROOT/$TARGET_DIR" ;;
esac
BIN="$TARGET_DIR/debug/topology-check"
REGISTRY="$ROOT/registries/workspace_topology.toml"
DOCUMENT="$ROOT/docs/WORKSPACE_TOPOLOGY.md"

echo "==> build topology-check"
cargo build -p registry-check --bin topology-check
test -x "$BIN"

echo "==> validate the frozen topology twice (determinism)"
"$BIN" --root "$ROOT" >"$FIRST"
"$BIN" --root "$ROOT" >"$SECOND"
cmp "$FIRST" "$SECOND"

echo "==> prove the published document is generated, not hand-authored"
DOC_BEFORE="$(sha256sum "$DOCUMENT" | cut -d' ' -f1)"
"$BIN" --root "$ROOT" --write >/dev/null
DOC_AFTER="$(sha256sum "$DOCUMENT" | cut -d' ' -f1)"
if [[ "$DOC_BEFORE" != "$DOC_AFTER" ]]; then
  echo "ERROR: docs/WORKSPACE_TOPOLOGY.md is not the regenerated bytes" >&2
  echo "  before=$DOC_BEFORE after=$DOC_AFTER" >&2
  exit 1
fi
grep -q '"document_matches":true' "$FIRST"

# Expectations that MOVE when the registry moves are derived from the registry,
# not hand-copied. The registry is an artifact independent of the binary under
# test, so this still cross-checks two sources rather than comparing output to
# itself. Values fixed by the PLAN (14 layers, 3 postures) stay literal on
# purpose: those are the enumerations the gate exists to freeze.
registry_scalar() {
  awk -v key="$1" '
    /^\[registry\]/ { inblock = 1; next }
    /^\[/ { inblock = 0 }
    inblock && $1 == key { gsub(/"/, "", $3); print $3; found = 1; exit }
    END { if (!found) { print "registry key " key " not found" > "/dev/stderr"; exit 42 } }
  ' "$REGISTRY"
}
EXPECT_CRATES="$(registry_scalar crate_count)"
EXPECT_CAPABILITIES="$(registry_scalar capability_count)"
EXPECT_BLOCKS="$(registry_scalar source_block_count)"
EXPECT_EDGES="$(registry_scalar required_dependency_count)"
EXPECT_ID_HASH="$(registry_scalar id_table_hash)"
EXPECT_SEMANTIC_HASH="$(registry_scalar semantic_contract_hash)"

echo "==> assert one event per crate, inventory row, block, and named edge"
test "$(grep -c '"event":"crate_checked"' "$FIRST")" -eq "$EXPECT_CRATES"
test "$(grep -c '"event":"capability_checked"' "$FIRST")" -eq "$EXPECT_CAPABILITIES"
test "$(grep -c '"event":"source_block_checked"' "$FIRST")" -eq "$EXPECT_BLOCKS"
test "$(grep -c '"event":"required_edge_checked"' "$FIRST")" -eq "$EXPECT_EDGES"
test "$(grep -c '"event":"posture_closure_checked"' "$FIRST")" -eq 3
test "$(grep -c '"event":"source_block_checked".*"outcome":"pass"' "$FIRST")" -eq "$EXPECT_BLOCKS"
grep -q '"event":"topology_registry_checked".*"id_table_hash":"'"$EXPECT_ID_HASH"'".*"semantic_contract_hash":"'"$EXPECT_SEMANTIC_HASH"'".*"violations":0.*"outcome":"pass"' "$FIRST"
if grep -q '"event":"topology_violation"' "$FIRST"; then
  echo "ERROR: unexpected topology violation event" >&2
  grep '"event":"topology_violation"' "$FIRST" >&2
  exit 1
fi

echo "==> report what is deferred rather than letting a green bar imply coverage"
# No composition crate is active, so every posture closure is deferred. Named
# edges may advance independently, so the Rust reader owns their live/deferred
# partition and the monotone set-floor. This shell gate checks the event schema
# and non-vacuous verdict, not a second hand-copied count.
grep '"event":"required_edge_coverage"' "$FIRST"
grep '"event":"posture_closure_checked"' "$FIRST" | grep -c '"outcome":"deferred"'
if ! grep -Eq '^\{"event":"required_edge_coverage","declared":[0-9]+,"evaluated_live":[0-9]+,"deferred":[0-9]+,"ratcheted_live_floor":[1-9][0-9]*,"unratcheted_live":[0-9]+,"outcome":"pass"\}$' "$FIRST"; then
  echo "ERROR: the named-edge ratchet event is absent, malformed, vacuous, or red" >&2
  exit 1
fi

echo "==> path independence: --registry and a foreign working directory"
( cd "$EVIDENCE_DIR" && "$BIN" --root "$ROOT" --registry "$REGISTRY" >"$EVIDENCE_DIR/third.ndjson" )
cmp "$FIRST" "$EVIDENCE_DIR/third.ndjson"

echo "==> seeded violation fixtures (each must fail with its exact code)"
FIXTURE_ROOT="$EVIDENCE_DIR/fixtures"
mkdir -p "$FIXTURE_ROOT"

# A fixture is a copy of exactly what the checker reads: the workspace manifest,
# the toolchain pin, the plan (the source blocks are re-read from it), the
# registries, the generated document, and every crate source the unsafe scan
# walks. Copied from the WORKING TREE, not from HEAD, so the gate exercises the
# change under review rather than the last commit.
new_fixture() {
  local dir="$FIXTURE_ROOT/$1"
  mkdir -p "$dir"
  cp -a \
    "$ROOT/Cargo.toml" \
    "$ROOT/rust-toolchain.toml" \
    "$ROOT/COMPREHENSIVE_PLAN_FOR_THE_DESIGN_OF_FRANKENGRAPHDB.md" \
    "$ROOT/registries" \
    "$ROOT/docs" \
    "$ROOT/crates" \
    "$ROOT/tools" \
    "$dir/"
  printf '%s' "$dir"
}

expect_failure() {
  local name="$1" expected_code="$2" dir="$3"
  local out="$EVIDENCE_DIR/$name.ndjson"
  if "$BIN" --root "$dir" >"$out" 2>"$EVIDENCE_DIR/$name.err"; then
    echo "ERROR: fixture $name did not fail" >&2
    exit 1
  fi
  if ! grep -q "\"code\":\"$expected_code\"" "$out"; then
    echo "ERROR: fixture $name failed with the wrong code (expected $expected_code)" >&2
    cat "$EVIDENCE_DIR/$name.err" >&2
    exit 1
  fi
  echo "    $name -> $expected_code"
}

seed_fixture() {
  local name="$1" expected_code="$2" python_edit="$3"
  local dir
  dir="$(new_fixture "$name")"
  python3 - "$dir/registries/workspace_topology.toml" "$python_edit" <<'PY'
import sys
path, edit = sys.argv[1], sys.argv[2]
old, new = edit.split("=>", 1)
text = open(path, encoding="utf-8").read()
assert text.count(old) == 1, f"fixture anchor {old!r} occurs {text.count(old)} times"
open(path, "w", encoding="utf-8").write(text.replace(old, new, 1))
PY
  expect_failure "$name" "$expected_code" "$dir"
}

# 1. An external dependency in a live manifest: the closed universe's whole
#    point, and the one fixture that mutates the TREE rather than the registry.
EXTERNAL_DIR="$(new_fixture external-dependency)"
python3 - "$EXTERNAL_DIR/crates/fgdb-resource/Cargo.toml" <<'PY'
import sys
path = sys.argv[1]
text = open(path, encoding="utf-8").read()
assert "[dependencies]" in text, "fixture expects a [dependencies] table"
open(path, "w", encoding="utf-8").write(
    text.replace("[dependencies]", '[dependencies]\nserde = "1"', 1)
)
PY
expect_failure external-dependency external_dependency "$EXTERNAL_DIR"

# 2. A crate the plan names, dropped from the registry.
seed_fixture dropped-crate crate_unregistered \
  'name = "fgdb-datalog"=>name = "fgdb-datalogue"'

# 3. A layer inversion expressed as a widened edge set.
seed_fixture widened-layer layer_allowed_edges_drift \
  'id = "chronicle"
title = "Chronicle"
source_order = 3
allowed_outgoing_layers = ["foundation", "unsafe_islands", "chronicle"]=>id = "chronicle"
title = "Chronicle"
source_order = 3
allowed_outgoing_layers = ["foundation", "unsafe_islands", "chronicle", "loom"]'

# 4. An inventory row deleted: coverage must catch it as residue.
seed_fixture dropped-capability inventory_coverage_incomplete \
  'source_phrase = "persistent union-find"=>source_phrase = "persistent union find"'

# 5. The one ratcheted live edge moves back to deferred. Other topology laws
#    also reject this fixture, but this exact code proves the set-floor itself
#    fired rather than borrowing their failure.
seed_fixture live-edge-redeferred required_edge_floor_regression \
  'name = "fgdb-calibrate"
layer = "foundation"
layer_position = 12
role = "Identity-bound calibration wrappers over the runtime'\''s e-process/conformal machinery."
role_basis = "layer_charter"
unsafe_policy = "forbid"
activation_status = "active"=>name = "fgdb-calibrate"
layer = "foundation"
layer_position = 12
role = "Identity-bound calibration wrappers over the runtime'\''s e-process/conformal machinery."
role_basis = "layer_charter"
unsafe_policy = "forbid"
activation_status = "planned"'

# 6. A ratchet with no members rejects nothing. This is the vacuity control,
#    and it must fire independently of the backwards-transition fixture.
seed_fixture empty-live-edge-floor required_edge_floor_vacuous \
  'required_dependency_live_floor = ["calibrate-over-asupersync"]=>required_dependency_live_floor = []'

echo "==> evidence retained at $EVIDENCE_DIR"
gate_pass "g0_topology_e2e"
